### ISSUE TITLE
Create a "CulterSpecific" Benchmark Category

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#1397]
The mono interpreter  has a INVARIANT_GLOBALIZATION option that can turn off some globalization features. We want to be able to measure the performance impact of it, but some benchmarks can not run with that option. For example, Perf.DateTimeCultureInfo:  https://github.com/dotnet/performance/blob/8aed638c9ee65c034fe0cca4ea2bdc3a68d2a6b5/src/benchmarks/micro/libraries/System.Globalization/Perf.DateTimeCultureInfo.cs

This issue is to create a benchmark category of those benchmarks to filter them out.

Here is the stack trace produced when running the mono interpreter with INVARIANT_GLOBALIZATION:

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Not a valid calendar for the given culture. (Parameter 'value')
Actual value was System.Globalization.HebrewCalendar.
   at System.Globalization.DateTimeFormatInfo.set_Calendar(Calendar value) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormatInfo.cs:line 477
   at System.Globalization.Tests.Perf_DateTimeCultureInfo.CreateHebrewIsraelCultureInfo() in /Users/naricc/workspace/performance-wasm/src/benchmarks/micro/libraries/System.Globalization/Perf.DateTimeCultureInfo.cs:line 44
   at System.Globalization.Tests.Perf_DateTimeCultureInfo..ctor() in /Users/naricc/workspace/performance-wasm/src/benchmarks/micro/libraries/System.Globalization/Perf.DateTimeCultureInfo.cs:line 39
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 860
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 872
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1961
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1932
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1810
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs:line 96
   at System.Activator.CreateInstance(Type type, Boolean nonPublic) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs:line 88
   at System.Activator.CreateInstance(Type type) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Activator.cs:line 42
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[BenchmarkDotNet.Parameters.ParameterInstances, BenchmarkDotNet, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null]].AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[ParameterInstances](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[ParameterInstances](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ImmutableConfig immutableConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2[[System.Type, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1[[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null]].ToArray()
   at System.Linq.Enumerable.ToArray[BenchmarkRunInfo](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /Users/naricc/workspace/performance-wasm/src/benchmarks/micro/Program.cs:line 37
[ERROR] FATAL UNHANDLED EXCEPTION: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentOutOfRangeException: Not a valid calendar for the given culture. (Parameter 'value')
Actual value was System.Globalization.HebrewCalendar.
   at System.Globalization.DateTimeFormatInfo.set_Calendar(Calendar value) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Globalization/DateTimeFormatInfo.cs:line 477
   at System.Globalization.Tests.Perf_DateTimeCultureInfo.CreateHebrewIsraelCultureInfo() in /Users/naricc/workspace/performance-wasm/src/benchmarks/micro/libraries/System.Globalization/Perf.DateTimeCultureInfo.cs:line 44
   at System.Globalization.Tests.Perf_DateTimeCultureInfo..ctor() in /Users/naricc/workspace/performance-wasm/src/benchmarks/micro/libraries/System.Globalization/Perf.DateTimeCultureInfo.cs:line 39
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 860
   --- End of inner exception stack trace ---
   at System.Reflection.RuntimeConstructorInfo.InternalInvoke(Object obj, Object[] parameters, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 872
   at System.RuntimeType.CreateInstanceMono(Boolean nonPublic, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1961
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean wrapExceptions, Boolean skipCheckThis, Boolean fillCache) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1932
   at System.RuntimeType.CreateInstanceDefaultCtor(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/mono/netcore/System.Private.CoreLib/src/System/RuntimeType.Mono.cs:line 1810
   at System.Activator.CreateInstance(Type type, Boolean nonPublic, Boolean wrapExceptions) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs:line 96
   at System.Activator.CreateInstance(Type type, Boolean nonPublic) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Activator.RuntimeType.cs:line 88
   at System.Activator.CreateInstance(Type type) in /Users/naricc/workspace/runtime-interpreter/src/libraries/System.Private.CoreLib/src/System/Activator.cs:line 42
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1[[BenchmarkDotNet.Parameters.ParameterInstances, BenchmarkDotNet, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null]].AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[ParameterInstances](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[ParameterInstances](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ImmutableConfig immutableConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2[[System.Type, System.Private.CoreLib, Version=5.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e],[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null]].MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1[[BenchmarkDotNet.Running.BenchmarkRunInfo, BenchmarkDotNet, Version=0.12.1.0, Culture=neutral, PublicKeyToken=null]].ToArray()
   at System.Linq.Enumerable.ToArray[BenchmarkRunInfo](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /Users/naricc/workspace/performance-wasm/src/benchmarks/micro/Program.cs:line 37

**Comment by naricc** [comment]
I intend to do this myself, but can't assign myself :)

**Comment by billwert** [comment]
@naricc Do you still intend to do this? :)

**Comment by naricc** [comment]
@billwert Sorry for the very late reply, some how that notification got lost. I don't think it is a priority for us to do this now.
