### ISSUE TITLE
Perf Process Tests failing in the lab

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/performance#1438]
```[2020/08/06 12:56:00][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2020/08/06 12:56:00][INFO]  ---> System.ArgumentException: Process with an Id of 15650 is not running.
[2020/08/06 12:56:00][INFO]    at System.Diagnostics.Process.GetProcessById(Int32 processId, String machineName) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1006
[2020/08/06 12:56:00][INFO]    at System.Diagnostics.Process.GetProcessById(Int32 processId) in /_/src/libraries/System.Diagnostics.Process/src/System/Diagnostics/Process.cs:line 1020
[2020/08/06 12:56:00][INFO]    at System.Diagnostics.Perf_Process.GetProcessById() in /home/helixbot/work/A71E08AD/p/performance/src/benchmarks/micro/libraries/System.Diagnostics/Perf_Process.cs:line 23
[2020/08/06 12:56:00][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_41.WorkloadActionNoUnroll(Int64 invokeCount) in /home/helixbot/work/A71E08AD/p/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp5.0/9740be27-f050-4a03-bb1f-d8f01c36edd0/9740be27-f050-4a03-bb1f-d8f01c36edd0.notcs:line 30825
[2020/08/06 12:56:00][INFO]    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
[2020/08/06 12:56:00][INFO]    at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
[2020/08/06 12:56:00][INFO]    at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
[2020/08/06 12:56:00][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_41.Run(IHost host, String benchmarkName) in /home/helixbot/work/A71E08AD/p/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp5.0/9740be27-f050-4a03-bb1f-d8f01c36edd0/9740be27-f050-4a03-bb1f-d8f01c36edd0.notcs:line 30151
[2020/08/06 12:56:00][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 384
[2020/08/06 12:56:00][INFO]    --- End of inner exception stack trace ---
[2020/08/06 12:56:00][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/mono/netcore/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 396
[2020/08/06 12:56:00][INFO]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/libraries/System.Private.CoreLib/src/System/Reflection/MethodBase.cs:line 49
[2020/08/06 12:56:00][INFO]    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in /home/helixbot/work/A71E08AD/p/performance/artifacts/bin/MicroBenchmarks/Release/netcoreapp5.0/9740be27-f050-4a03-bb1f-d8f01c36edd0/9740be27-f050-4a03-bb1f-d8f01c36edd0.notcs:line 149
```

**Comment by DrewScoggins** [comment]
I will update this with more info later

**Comment by adamsitnik** [comment]
it's a very weird exception, the setup sets the field to its own PID and afterward, the benchmark is just using it:

https://github.com/dotnet/performance/blob/1c5e64a3a0d3619a5b72be63cd54add5156532cc/src/benchmarks/micro/libraries/System.Diagnostics/Perf_Process.cs#L19-L23

Is this specific to mono only?

**Comment by DrewScoggins** [comment]
I think that this was happening on both CoreCLR and Mono.

Coreclr: https://helix.dot.net/api/2019-06-17/jobs/bf571916-434c-45ea-a150-8aff02ad93b9/workitems/x64.micro.net5.0.Partition15/console?access_token=

Mono: https://helix.dot.net/api/2019-06-17/jobs/8db09b5e-8016-452f-bf9b-049300db548f/workitems/x64.micro_mono.net5.0.Partition15/console?access_token=

**Comment by danmosemsft** [comment]
Presumably only on Linux?
