### ISSUE TITLE
py . diff is broken for GC benchmarks.

### ISSUE THREAD

**Issue by cshung** [dotnet/performance#1507]
After https://github.com/dotnet/performance/pull/1391, the generated test status file is no longer valid yaml, this cause the deserializer to fail when running `py . diff`.

If we wanted the nice test status file format, we probably need to hack the deserializer so that it will accept it.

@ivdiazsa

**Comment by ivdiazsa** [comment]
Can you provide an example? I've been working with `diff` with these changes already merged, and everything works fine for me.

**Comment by cshung** [comment]
```
C:\Dev\performance\src\benchmarks\gc>py . diff bench/suite/normal_server.yaml
Error in C:\Dev\performance\src\benchmarks\gc\bench\suite\normal_server.yaml.out\a__only_config__0gb__0.yaml
Traceback (most recent call last):
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File ".\__main__.py", line 9, in <module>
    run_command(ALL_COMMANDS)
  File ".\src\commonlib\command.py", line 87, in run_command
    run_command_worker(commands, cmd_and_args)
  File ".\src\commonlib\command.py", line 243, in run_command_worker
    cast(Callable[[Any], None], command.fn)(args)
  File ".\src\analysis\report.py", line 516, in diff
    process=args.process,
  File ".\src\analysis\report.py", line 550, in diff_for_jupyter
    process=process,
  File ".\src\analysis\diffable.py", line 166, in get_diffables
    max_iterations=max_iterations,
  File ".\src\analysis\diffable.py", line 242, in get_diffables_from_bench_file
    for t in filtered_all_combinations
  File ".\src\commonlib\collection_util.py", line 72, in make_mapping
    for k, v in pairs:
  File ".\src\analysis\diffable.py", line 242, in <genexpr>
    for t in filtered_all_combinations
  File ".\src\analysis\diffable.py", line 131, in _get_for_single_test
    for iteration in get_test_paths_for_each_iteration(bench_and_path, test, max_iterations)
  File ".\src\analysis\diffable.py", line 131, in <listcomp>
    for iteration in get_test_paths_for_each_iteration(bench_and_path, test, max_iterations)
  File ".\src\commonlib\bench_file.py", line 1260, in to_test_result
    trace_path=self.load_trace_file_path_if_success(),
  File ".\src\commonlib\bench_file.py", line 1264, in load_trace_file_path_if_success
    test_status = self.load_test_status()
  File ".\src\commonlib\bench_file.py", line 1255, in load_test_status
    return load_yaml(TestRunStatus, self.test_status_path)
  File ".\src\commonlib\parse_and_serialize.py", line 84, in load_yaml
    cls, safe_load(f), path, PropPath.root(f"load_yaml {cls}"), all_optional
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\main.py", line 994, in safe_load
    return load(stream, SafeLoader, version)
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\main.py", line 949, in load
    return loader._constructor.get_single_data()
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\constructor.py", line 111, in get_single_data
    node = self.composer.get_single_node()
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\composer.py", line 78, in get_single_node
    document = self.compose_document()
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\composer.py", line 101, in compose_document
    node = self.compose_node(None, None)
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\composer.py", line 138, in compose_node
    node = self.compose_mapping_node(anchor)
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\composer.py", line 218, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\composer.py", line 111, in compose_node
    if self.parser.check_event(AliasEvent):
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\parser.py", line 140, in check_event
    self.current_event = self.state()
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\parser.py", line 603, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\scanner.py", line 170, in check_token
    self.fetch_more_tokens()
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\scanner.py", line 311, in fetch_more_tokens
    return self.fetch_double()
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\scanner.py", line 729, in fetch_double
    self.fetch_flow_scalar(style='"')
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\scanner.py", line 738, in fetch_flow_scalar
    self.tokens.append(self.scan_flow_scalar(style))
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\scanner.py", line 1383, in scan_flow_scalar
    chunks.extend(self.scan_flow_scalar_non_spaces(double, start_mark))
  File "C:\Users\andrewau\AppData\Local\Programs\Python\Python37\lib\site-packages\ruamel\yaml\scanner.py", line 1460, in scan_flow_scalar_non_spaces
    self.reader.get_mark(),
ruamel.yaml.scanner.ScannerError: while scanning a double-quoted scalar
  in "C:\Dev\performance\src\benchmarks\gc\bench\suite\normal_server.yaml.out\a__only_config__0gb__0.yaml", line 7, column 3
found unknown escape character 'D'
  in "C:\Dev\performance\src\benchmarks\gc\bench\suite\normal_server.yaml.out\a__only_config__0gb__0.yaml", line 10, column 14
```

C:\Dev\performance\src\benchmarks\gc\bench\suite\normal_server.yaml.out\a__only_config__0gb__0.yaml
```
success: True
trace_file_name: a__only_config__0gb__0.etl
process_id: 13200
seconds_taken: 20.750174
test:
stdout:
  "The flag -pohsi is only supported on .NET Core 5+. Skipping in this run.
  The flag -pohpi is only supported on .NET Core 5+. Skipping in this run.
  The flag -pohfi is only supported on .NET Core 5+. Skipping in this run.
  CoreRun C:\Dev\performance\artifacts\bin\GCPerfSim\release\netcoreapp5.0\GCPerfSim.dll -tc 6 -tagb 300.0 -tlgb 0.0 -lohar 0 -sohsi 0 -lohsi 0 -pohsi 0 -sohpi 0 -lohpi 0 -pohpi 0 -sohfi 0 -lohfi 0 -pohfi 0 -allocType reference -testKind time
  allocating 53,687,091,200 per thread
  Running 64-bit? True
  PID: 13200
  Running 6 threads.
  time, ReferenceItem, tlgb 0, tagb 50, totalMins 0, buckets:
      100-4000; surv every 0; pin every 0; weight 1000
  Thread 0 stopping phase after 51200MB
  Thread 5 stopping phase after 51200MB
  Thread 1 stopping phase after 51200MB
  Thread 3 stopping phase after 51200MB
  Thread 4 stopping phase after 51200MB
  Thread 2 stopping phase after 51200MB
  === STATS ===
  seconds_taken: 18.9833144
  collection_counts: [12753, 167, 0]
  num_created_with_finalizers: 0
  num_finalized: 0
  final_total_memory_bytes: 20509688
  final_heap_size_bytes: 916704
  final_fragmentation_bytes: 288"
gcperfsim_result:
```

**Comment by ivdiazsa** [comment]
I see the problem. Since the output contains a Windows path, say it contains for example `C:\Git`, the serializer is treating `\G` as a single character, when in reality the backslash has no hidden meaning here. The fix is to further process the `stdout` string and escape these characters to make them `\\` instead. I manually changed them in the _yaml_ file and it worked fine. Or we could revert this change and deal with the bad printing layout the serializer does for multiline values by default. Hacking into the built-in Python serializer seems a more hazardous and time-consuming task than it's worth.

**Comment by ivdiazsa** [comment]
Further looking at it, replacing `\` with `\\` might potentially ruin the newline character replacement that is done to print it nicely. If this is the case, then we might just need to deal with the badly formatted output the Python serializer creates.
