### ISSUE TITLE
Failing assert in ILogB benchmark

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#1647]
I've merged one big PR of mine and some CI legs went red after that. I thought it was my fault, but according to the [logs](https://helixre8s23ayyeko0k025g8.blob.core.windows.net/dotnet-performance-refs-heads-master-b0e291e414a14b52b3/Partition0/console.94d3d474.log?sv=2019-07-07&se=2021-02-24T12%3A04%3A47Z&sr=c&sp=rl&sig=IWpBGVp7VJ0YkF6VTB3etbJSGxm7l5EWkCWhKYaJowk%3D) the windows CI leg for .NET 6 failed because of the following condition:

https://github.com/dotnet/performance/blob/4e14ecc54759224121b807c70e46fb1d9ee0e7d6/src/benchmarks/micro/runtime/Math/Functions/Double/ILogB.cs#L31

```log
[2021/02/04 12:35:55][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2021/02/04 12:35:55][INFO]  ---> System.Exception: Expected Result                 2499; Actual Result                    0
[2021/02/04 12:35:55][INFO]    at System.MathBenchmarks.Double.ILogBTest() in C:\h\w\A401087B\p\src\benchmarks\micro\runtime\Math\Functions\Double\ILogB.cs:line 33
[2021/02/04 12:35:55][INFO]    at System.MathBenchmarks.Double.ILogB() in C:\h\w\A401087B\p\src\benchmarks\micro\runtime\Math\Functions\Double\ILogB.cs:line 18
[2021/02/04 12:35:55][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_354.WorkloadActionUnroll(Int64 invokeCount) in C:\h\w\A401087B\p\artifacts\bin\MicroBenchmarks\Release\net6.0\aba3fe28-ae33-452f-9d08-31981993ac55\aba3fe28-ae33-452f-9d08-31981993ac55.notcs:line 210808
```

I was able to reproduce it on my PC:

```cmd
git clone https://github.com/dotnet/performance.git repro
py .\repro\scripts\benchmarks_ci.py -f net6.0 --filter System.MathBenchmarks.Double.ILogB
```

@tannergooding is this expected?

**Comment by adamsitnik** [comment]
Minimum repro without perf repo involved:

```cs
using System;

namespace minimum
{
    class Program
    {
        private const double iLogBDelta = 0.0004;
        private const int iLogBExpectedResult = 2499;
        
        static void Main()
        {
            int result = 0;
            double value = 1.0;

            for (int iteration = 0; iteration < 5000; iteration++)
            {
                result += Math.ILogB(value);
                value += iLogBDelta;
            }

            if (result != iLogBExpectedResult)
            {
                throw new Exception($"Expected Result {iLogBExpectedResult,20:g17}; Actual Result {result,20:g17}");
            }
        }
    }
}
```
