### ISSUE TITLE
Failure when collecting profile ETL in Startup

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/performance#1689]
```
[2021/02/18 04:09:17][INFO] Fatal error. Internal CLR error. (0x80131506)
[2021/02/18 04:09:17][INFO]    at System.Diagnostics.Tracing.NativeRuntimeEventSource.ThreadPoolWorkerThreadWait(UInt32, UInt32, UInt16)
[2021/02/18 04:09:17][INFO]    at System.Threading.PortableThreadPool+WorkerThread+<>c.<.cctor>b__8_0()
[2021/02/18 04:09:17][INFO]    at System.Threading.LowLevelLifoSemaphore.WaitForSignal(Int32)
[2021/02/18 04:09:17][INFO]    at System.Threading.LowLevelLifoSemaphore.Wait(Int32, Boolean)
[2021/02/18 04:09:17][INFO]    at System.Threading.PortableThreadPool+WorkerThread.WorkerThreadStart()
[2021/02/18 04:09:17][INFO]    at System.Threading.Thread.StartCallback()
[2021/02/18 04:09:17][ERROR] Process exited with status 2148734214
```

When trying to collect the profile ETL in our startup tests we get the following CLR error.

**Comment by billwert** [comment]
Looks like it is Looks like it is dotnet/runtime#48470.

**Comment by danmoseley** [comment]
That issue is now fixed
