### ISSUE TITLE
Crash in BDN for WASM Runs

### ISSUE THREAD

**Issue by DrewScoggins** [dotnet/performance#1720]
Posted below is the output of failures in most of the WASM runs since Feb 25.
@adamsitnik @naricc 

```
[2021/03/10 08:05:24][INFO] $ dotnet run --project /home/helixbot/work/B12909C3/p/performance/src/benchmarks/micro/MicroBenchmarks.csproj --configuration Release --framework net6.0 --no-restore --no-build -- --anyCategories Libraries Runtime "" --category-exclusion-filter NoInterpreter NoWASM NoMono --wasmMainJS /home/helixbot/work/B12909C3/p/dotnet-wasm/runtime-test.js --wasmEngine /home/helixbot/.jsvu/v8 --customRuntimePack /home/helixbot/work/B12909C3/p/dotnet-wasm "" --partition-count 30 --partition-index 10 --artifacts /home/helixbot/work/B12909C3/p/artifacts/BenchmarkDotNet.Artifacts --packages /home/helixbot/work/B12909C3/p/performance/artifacts/packages --runtimes wasm
[2021/03/10 08:05:25][INFO] // Validating benchmarks:
[2021/03/10 08:05:26][INFO] // ***** BenchmarkRunner: Start   *****
[2021/03/10 08:05:26][INFO] // ***** Found 101 benchmark(s) in total *****
[2021/03/10 08:05:26][INFO] // ***** Building 1 exe(s) in Parallel: Start   *****
[2021/03/10 08:05:26][INFO] // start dotnet restore --packages "/home/helixbot/work/B12909C3/p/performance/artifacts/packages" /p:DebugType=portable /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in /home/helixbot/work/B12909C3/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/18211db1-1f37-47fb-bfc8-2545546307fb
[2021/03/10 08:05:33][INFO] // command took 7.29s and exited with 0
[2021/03/10 08:05:33][INFO] // start dotnet build -c Release /p:DebugType=portable --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true /p:NuGetPackageRoot="/home/helixbot/work/B12909C3/p/performance/artifacts/packages" in /home/helixbot/work/B12909C3/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/18211db1-1f37-47fb-bfc8-2545546307fb
[2021/03/10 08:05:48][INFO] // command took 14.11s and exited with 1
[2021/03/10 08:05:48][INFO] // start dotnet build -c Release /p:DebugType=portable --no-restore --no-dependencies /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true /p:NuGetPackageRoot="/home/helixbot/work/B12909C3/p/performance/artifacts/packages" in /home/helixbot/work/B12909C3/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/18211db1-1f37-47fb-bfc8-2545546307fb
[2021/03/10 08:05:51][INFO] // command took 3.3s and exited with 0
[2021/03/10 08:05:51][INFO] // ***** Done, took 00:00:25 (25.04 sec)   *****
[2021/03/10 08:05:51][INFO] // Found 1 benchmarks:
[2021/03/10 08:05:51][INFO] //   ByteMark.BenchBitOps: Job-YGPUSN(PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1)
[2021/03/10 08:05:51][INFO] 
[2021/03/10 08:05:51][INFO] // **************************
[2021/03/10 08:05:51][INFO] // Benchmark: ByteMark.BenchBitOps: Job-YGPUSN(PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1)
[2021/03/10 08:05:51][INFO] // *** Execute ***
[2021/03/10 08:05:51][INFO] // Launch: 1 / 1
[2021/03/10 08:05:51][INFO] // Execute: /home/helixbot/.jsvu/v8 --expose_wasm runtime.js -- --run 18211db1-1f37-47fb-bfc8-2545546307fb.dll --benchmarkName "ByteMark.BenchBitOps" --job "PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1" --benchmarkId 0  in /home/helixbot/work/B12909C3/p/performance/artifacts/bin/MicroBenchmarks/Release/net6.0/18211db1-1f37-47fb-bfc8-2545546307fb/bin/net6.0/browser-wasm/publish/output
[2021/03/10 08:05:51][INFO] Failed to set up high priority. Make sure you have the right permissions. Message: Permission denied
[2021/03/10 08:06:51][INFO] console.info: Arguments: --run,18211db1-1f37-47fb-bfc8-2545546307fb.dll,--benchmarkName,ByteMark.BenchBitOps,--job,PowerPlanMode=00000000-0000-0000-0000-000000000000, Runtime=Wasm, Arguments=/p:DebugType=portable, Toolchain=Wasm, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1,--benchmarkId,0
[2021/03/10 08:06:51][INFO] console.debug: MONO_WASM: Initializing mono runtime
[2021/03/10 08:06:51][INFO] console.debug: MONO_WASM: ICU data archive(s) loaded, disabling invariant mode
[2021/03/10 08:06:51][INFO] console.debug: mono_wasm_runtime_ready fe00e07a-5519-4dfe-b35a-f867dbaf2e28
[2021/03/10 08:06:51][INFO] console.info: Initializing.....
[2021/03/10 08:06:51][INFO] // BeforeAnythingElse
[2021/03/10 08:06:51][INFO] Unhandled exception. System.IO.IOException: Broken pipe
[2021/03/10 08:06:51][INFO]    at System.IO.LegacyFileStreamStrategy.WriteNative(ReadOnlySpan`1 source)
[2021/03/10 08:06:51][INFO]    at System.IO.LegacyFileStreamStrategy.FlushWriteBuffer(Boolean calledFromFinalizer)
[2021/03/10 08:06:51][INFO]    at System.IO.LegacyFileStreamStrategy.Flush(Boolean flushToDisk)
[2021/03/10 08:06:51][INFO]    at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
[2021/03/10 08:06:51][INFO]    at System.IO.StreamWriter.WriteLine(String value)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Loggers.SynchronousProcessOutputLoggerWithDiagnoser.ProcessInput()
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Toolchains.Executor.Execute(Process process, BenchmarkCase benchmarkCase, SynchronousProcessOutputLoggerWithDiagnoser loggerWithDiagnoser, ILogger logger, ConsoleExitHandler consoleExitHandler)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Toolchains.Executor.Execute(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, ArtifactsPaths artifactsPaths, String args, IDiagnoser diagnoser, IResolver resolver)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Toolchains.Executor.Execute(ExecuteParameters executeParameters)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunExecute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver, IDiagnoser diagnoser, Boolean& success)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Execute(ILogger logger, BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, IToolchain toolchain, BuildResult buildResult, IResolver resolver)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.RunCore(BenchmarkCase benchmarkCase, BenchmarkId benchmarkId, ILogger logger, IResolver resolver, BuildResult buildResult)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo benchmarkRunInfo, Dictionary`2 buildResults, IResolver resolver, ILogger logger, List`1 artifactsToCleanup, String resultsFolderPath, String logFilePath, StartedClock& runChronometer)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkRunnerClean.Run(BenchmarkRunInfo[] benchmarkRunInfos)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
[2021/03/10 08:06:51][INFO]    at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
[2021/03/10 08:06:51][INFO]    at MicroBenchmarks.Program.Main(String[] args) in /home/helixbot/work/B12909C3/p/performance/src/benchmarks/micro/Program.cs:line 41
[2021/03/10 08:06:51][INFO] $ popd
[2021/03/10 08:06:51][ERROR] Process exited with status 134
```

**Comment by naricc** [comment]
I have been able to reproduce this locally, but I don't understand the cause yet. It seems to be failing in the toolchain, after the benchmark has already completed running. Maybe its the harness is not getting the afterall message from the benchmark for some reason?

**Comment by naricc** [comment]
This seems to go away when I redirect standard output, which has made it annoying to debug. But based on dates, and the changes made, is likely related to this change: https://github.com/dotnet/runtime/commit/8be118e5025761f5d8ab1272a0987a73ad1efe9b

**Comment by naricc** [comment]
Ok, I think I now understand this issue.

Normally, there is two way communication between the benchmark program (the program generated from BenchmarkProgram.txt in BDN), and the BDN harness.

The benchmark program sends notifications to the harness about its progress, and then the program waits for an acknowledgement that those notifications are recieved.

However, Wasm cannot read from the standard input, due to the limitations of the platform. Instead it just sends the notifications, but does not wait for acknowledgements from the harness. Note that the harness is still *sending* the notifications, but the wasm application has no way of reading them.

 This is a problem because the benchmark program can race ahead of the harness, and finish before the harness sends all the acknowledgements. Then, when the harness does send the acknowledgement, it will fail with a closed pipe because the benchmark program has terminated.
 
 This is a race condition, and probably wan't happening before because wasm was just too slow to finish before the harness was ready to deal with it.
 
 Proposed solution: Just catch this exception of the platform is wasm, we don't really need the acknowledgements.

**Comment by naricc** [comment]
@DrewScoggins Hey, I was just noticing we fixed this, but didn't close the issue. It seems I am not able to close it?

**Comment by DrewScoggins** [comment]
I thought we had linked up this issue with the PR, but it looks like that didn't happen. Good catch, closing.
