### ISSUE TITLE
MicroBenchmarks fail to build due to SslStreamTests not finding a file

### ISSUE THREAD

**Issue by carlossanlop** [dotnet/performance#1791]
### Problem

I recently fetched the latest bits from this repo, and I am unable to run MicroBenchmarks because the SslStreamTests class is complaining that this file is missing:

 `/home/carlos/performance/libraries/System.Net.Http/testservereku.contoso.com.pfx`

It's not missing, it's just that the path is incorrect. The file actually lives in:

`/home/carlos/performance/src/benchmarks/micro/libraries/System.Net.Http/testservereku.contoso.com.pfx`

### Root cause

The method `System.Net.Tests.Common.Configuration.Certificates.GetCertificate` is incorrectly constructing the full path of that file, assuming the path will always be relative to the location of `MicroBenchmarks.csproj`. Ideally, the method should construct an absolute path:

https://github.com/dotnet/performance/blob/d7dac8a7ca12a28d099192f8a901cf8e30361384/src/benchmarks/micro/libraries/System.Net.Http/Configuration.Certificates.cs#L27-L32

It's an issue for me because I run benchmarks from a bash script and all the paths I pass to it are absolute paths.

One potential way to get this fixed is to modify the csproj so that it always copies the *.pfx files to the artifacts folder, then obtain their location as a relative path to the generated MicroBenchmarks assembly.

### Workaround

I'm commenting the code inside `SslStreamTests.cs`, `SslStreamTests.Context.cs` and `SslStreamTests.Protocols.cs`.

### Question

@adamsitnik  Why is it still excecuting code from SslStreamTests? If you look at my command below, I passed a filter that is completely unrelated to SslStreamTests.

### Command

```
/home/carlos/runtime_base/.dotnet/dotnet run --project /home/carlos/performance/src/benchmarks/micro/MicroBenchmarks.csproj \
    -c Release \
    -f net6.0 \
    --artifacts /home/carlos/perf_before \
    --coreRun /home/carlos/runtime_base/artifacts/bin/testhost/net6.0-Linux-Release-x64/shared/Microsoft.NETCore.App/6.0.0/corerun \
    --filter System.IO.Tests.Perf_Directory*
```

### Output

```
Unhandled exception. System.TypeInitializationException: The type initializer for 'System.Net.Security.Tests.SslStreamTests' threw an exception.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/home/carlos/performance/libraries/System.Net.Http/testservereku.contoso.com.pfx'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at System.IO.File.ReadAllBytes(String path)
   at System.Net.Test.Common.Configuration.Certificates.GetCertificate(String certificateFileName) in /home/carlos/performance/src/benchmarks/micro/libraries/System.Net.Http/Configuration.Certificates.cs:line 28
   at System.Net.Test.Common.Configuration.Certificates.GetServerCertificate() in /home/carlos/performance/src/benchmarks/micro/libraries/System.Net.Http/Configuration.Certificates.cs:line 17
   at System.Net.Security.Tests.SslStreamTests..cctor() in /home/carlos/performance/src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.cs:line 23
   --- End of inner exception stack trace ---
   at System.Net.Security.Tests.SslStreamTests.get_SupportsTls13() in /home/carlos/performance/src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.Protocols.cs:line 17
   at System.Net.Security.Tests.SslStreamTests.TlsProtocols()+MoveNext() in /home/carlos/performance/src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.Protocols.cs:line 22
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.ToArray(Object sourceValue, MemberInfo memberInfo, Type type)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /home/carlos/performance/src/benchmarks/micro/Program.cs:line 41
```

**Comment by BruceForstall** [comment]
@billwert @DrewScoggins @adamsitnik
