### ISSUE TITLE
Unable to build GC benchmarks

### ISSUE THREAD

**Issue by alexcovington** [dotnet/performance#1816]
I'm unable to build the GC benchmarks using [these instructions](https://github.com/dotnet/performance/tree/main/src/benchmarks/gc). There appears to be a parsing error when I run the `python3 . setup` command:

```
$ python3 . setup
Traceback (most recent call last):
File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "./__main__.py", line 9, in <module>
run_command(ALL_COMMANDS)
File "./src/commonlib/command.py", line 87, in run_command
run_command_worker(commands, cmd_and_args)
File "./src/commonlib/command.py", line 233, in run_command_worker
cast(Callable[[], None], command.fn)()
File "./src/commonlib/setup.py", line 26, in setup
write_host_info()
File "./src/commonlib/host_info.py", line 276, in write_host_info
write_yaml_file(HOST_INFO_PATH, _get_host_info(built), overwrite=True)
File "./src/commonlib/host_info.py", line 114, in _get_host_info
return {OS.posix: lambda _: _get_host_info_posix(), OS.windows: _get_host_info_windows}[
File "./src/commonlib/host_info.py", line 114, in <lambda>
return {OS.posix: lambda _: _get_host_info_posix(), OS.windows: _get_host_info_windows}[
File "./src/commonlib/host_info.py", line 152, in _get_host_info_posix
l1d_cache_kb = get_opt_kb("L1d cache")
File "./src/commonlib/host_info.py", line 139, in get_opt_kb
return map_option(opt, lambda s: int(remove_str_end(s, "K")))
File "./src/commonlib/option.py", line 25, in map_option
return None if t is None else cb(t)
File "./src/commonlib/host_info.py", line 139, in <lambda>
return map_option(opt, lambda s: int(remove_str_end(s, "K")))
File "./src/commonlib/util.py", line 43, in remove_str_end
assert s.endswith(end), f"Expected {s} to end with {end}"
AssertionError: Expected 4 MiB to end with K 
```

Looks like it's failing when trying to parse `lscpu` output. Relevant section of `lscpu` output:

```
L1d cache:                       4 MiB
L1i cache:                       4 MiB
L2 cache:                        64 MiB
L3 cache:                        512 MiB
```

**Comment by Maoni0** [comment]
@ivdiazsa could you please take a look at this? also CC-ing @mangod9, this is prevent AMD folks from building our infra.

**Comment by ivdiazsa** [comment]
Judging by the outputs provided, I'm assuming this is on Linux. Is this correct?
I ask to know where to begin investigating to work on a fix.

**Comment by alexcovington** [comment]
@ivdiazsa Yes, this is on Ubuntu 20.04.

Output of `lsb_release`:

```sh
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.2 LTS
Release:        20.04
Codename:       focal
```
