### ISSUE TITLE
GC benchmarks crash during run

### ISSUE THREAD

**Issue by alexcovington** [dotnet/performance#1852]
When I try to run the GC benchmarks, the suite crashes during the `suite-run` step [here](https://github.com/dotnet/performance/tree/main/src/benchmarks/gc#running).

Steps to reproduce:

```sh
## Build CoreCLR and Core_Root
$ mkdir -p ~/projects && git clone https://github.com/dotnet/runtime ~/projects/runtime && cd ~/projects/runtime
$ ./build.sh clr+libs -c Release -lc Release -rc Release
$ cd src/tests
$ ./build.sh -release -generatelayoutonly

## Setup GC tests
$ git clone https://github.com/dotnet/performance ~/projects/performance && cd ~/projects/performance/src/benchmarks/gc
$ python3 -m pip install -r src/requirements.txt
$ cd src/exec/GCPerfSim
$ dotnet build -c release
$ cd ../../analysis/managed-lib
$ dotnet publish
$ cd ../../../
$ python3 . setup
$ python3 . suite-create bench/suite/ --coreclrs /home/amd/projects/runtime/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/  --overwrite 
```

When I run the tests, I see this error:

```sh
## Run the tests
$ python3 . suite-run bench/suite/suite.yaml 
=== /home/amd/projects/performance/src/benchmarks/gc/bench/suite/normal_workstation.yaml ===

16:18:19 Running defgcperfsim__a__only_config__0gb__0
/home/amd/projects/runtime-master/artifacts/tests/coreclr/Linux.x64.Release/Tests/Core_Root/corerun /home/amd/projects/performance/artifacts/bin/GCPerfSim/release/netcoreapp3.1/GCPerfSim.dll -tc 1 -tagb 150.0 -tlgb 0.0 -lohar 0 -pohar 0 -sohsi 0 -lohsi 0 -pohsi 0 -sohsr 100-4000 -lohsr 102400-204800 -pohsr 100-204800 -sohpi 0 -lohpi 0 -sohfi 0 -lohfi 0 -pohfi 0 -allocType reference -testKind time (cwd /home/amd/projects/performance/src/benchmarks/gc/bench/suite/normal_workstation.yaml.out/defgcperfsim__a__only_config__0gb__0)
16:18:20 Running defgcperfsim__a__only_config__0gb__1
16:18:20 Running defgcperfsim__a__only_config__2gb__0
16:18:20 Running defgcperfsim__a__only_config__2gb__1
16:18:21 Running defgcperfsim__a__only_config__2gb_pinning__0
16:18:21 Running defgcperfsim__a__only_config__2gb_pinning__1
16:18:21 Running defgcperfsim__a__only_config__20gb__0
16:18:22 Running defgcperfsim__a__only_config__20gb__1

=== /home/amd/projects/performance/src/benchmarks/gc/bench/suite/normal_server.yaml ===

Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "./__main__.py", line 9, in <module>
    run_command(ALL_COMMANDS)
  File "./src/commonlib/command.py", line 87, in run_command
    run_command_worker(commands, cmd_and_args)
  File "./src/commonlib/command.py", line 243, in run_command_worker
    cast(Callable[[Any], None], command.fn)(args)
  File "./src/suite.py", line 160, in suite_run
    run_test(
  File "./src/exec/run_tests.py", line 141, in run_test
    check_no_test_processes()
  File "./src/exec/run_single_test.py", line 215, in check_no_test_processes
    check_no_processes(TEST_PROCESS_NAMES)
  File "./src/commonlib/util.py", line 842, in check_no_processes
    assert name not in proc.name().lower(), (
AssertionError: 'corerun' is already running
Try: `pkill -f corerun`
```

I've retried the benchmarks after running `pkill -f corerun`, `pkill -f dotnet`, and after a full reboot and am unable to resolve the error.

Output of `dotnet --info`:

```sh
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.4.21255.9
 Commit:    950e4949a7

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /home/amd/.dotnet/sdk/6.0.100-preview.4.21255.9/

Host (useful for support):
  Version: 6.0.0-preview.4.21253.7
  Commit:  bfd6048a60

.NET SDKs installed:
  3.1.409 [/home/amd/.dotnet/sdk]
  5.0.203 [/home/amd/.dotnet/sdk]
  6.0.100-preview.3.21202.5 [/home/amd/.dotnet/sdk]
  6.0.100-preview.4.21255.9 [/home/amd/.dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.15 [/home/amd/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [/home/amd/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.3.21201.13 [/home/amd/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.4.21253.5 [/home/amd/.dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.15 [/home/amd/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [/home/amd/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.3.21201.4 [/home/amd/.dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.4.21253.7 [/home/amd/.dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Please let me know if there is anything else I can try or if there is any other information I can provide.

**Comment by alexcovington** [comment]
Resolved, this was an issue with `dotnet-trace` not properly being in the `$PATH`.

**Comment by danmoseley** [comment]
Seems like the error could be more helpful though.
