### ISSUE TITLE
System.IO.FileLoadException when running diff for GC benchmarks on Windows

### ISSUE THREAD

**Issue by alexcovington** [dotnet/performance#1874]
I'm getting a System.IO.FileLoadException when I try to run `py . diff` after running the GC benchmarks.

Steps to reproduce:

```sh
$ cd src\benchmarks\gc
$ py -m pip install -r src\requirements.txt
$ py -m pip install git+https://github.com/pythonnet/pythonnet
$ cd src\exec\GCPerfSim
$ dotnet build -c release
$ cd ..\..\analysis\managed-lib
$ dotnet publish
$ cd ..\..\exec\env
$ .\build.cmd
$ cd ..\..\..\
$ py . setup
$ py . suite-create bench/suite --coreclrs C:\Users\acovingt\source\repos\runtime-master\artifacts\tests\coreclr\windows.x64.Release\Tests\Core_Root\
$ py . run bench\suite\normal_workstation.yaml
```

When I run the diff step, I get the following error:

```sh
$ py . diff bench\suite\normal_workstation.yaml
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Program Files\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\acovingt\source\repos\performance\src\benchmarks\gc\__main__.py", line 9, in <module>
    run_command(ALL_COMMANDS)
  File "C:\Users\acovingt\source\repos\performance\src\benchmarks\gc\src\commonlib\command.py", line 87, in run_command
    run_command_worker(commands, cmd_and_args)
  File "C:\Users\acovingt\source\repos\performance\src\benchmarks\gc\src\commonlib\command.py", line 243, in run_command_worker
    cast(Callable[[Any], None], command.fn)(args)
  File "C:\Users\acovingt\source\repos\performance\src\benchmarks\gc\src\analysis\report.py", line 508, in diff
    traces=ProcessedTraces(),
  File "C:\Users\acovingt\source\repos\performance\src\benchmarks\gc\src\analysis\process_trace.py", line 289, in __init__
    self.clr = get_clr()
  File "C:\Users\acovingt\source\repos\performance\src\benchmarks\gc\src\analysis\clr.py", line 266, in get_clr
    AddReference(path)
System.IO.FileLoadException: Could not load file or assembly 'C:\\Users\\acovingt\\source\\repos\\performance\\artifacts\\bin\\GCPerf\\Debug\\netstandard2.0\\publish\\GCPerf.dll' or one of its dependencies. The given assembly name or codebase was invalid. (Exception from HRESULT: 0x80131047)
File name: 'C:\\Users\\acovingt\\source\\repos\\performance\\artifacts\\bin\\GCPerf\\Debug\\netstandard2.0\\publish\\GCPerf.dll'
   at System.Reflection.AssemblyName.nInit(RuntimeAssembly& assembly, Boolean forIntrospection, Boolean raiseResolveEvent)
   at System.Reflection.RuntimeAssembly.CreateAssemblyName(String assemblyString, Boolean forIntrospection, RuntimeAssembly& assemblyFromResolveEvent)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.Reflection.Assembly.Load(String assemblyString)
   at Python.Runtime.AssemblyManager.LoadAssembly(String name)
   at Python.Runtime.CLRModule.AddReference(String name)
```

I've confirmed that `C:\Users\acovingt\source\repos\performance\artifacts\bin\GCPerf\Debug\netstandard2.0\publish\GCPerf.dll` does exist:

```
$  Test-Path C:\Users\acovingt\source\repos\performance\artifacts\bin\GCPerf\Debug\netstandard2.0\publish\GCPerf.dll
True
```

`dotnet --info` output:

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.100-preview.2.21155.3
 Commit:    1a9103db2d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\

Host (useful for support):
  Version: 6.0.0-preview.2.21154.6
  Commit:  3eaf1f316b

.NET SDKs installed:
  5.0.103 [C:\Program Files\dotnet\sdk]
  5.0.400-preview.21277.10 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.1.21103.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.2.21154.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.2.21154.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

Please let me know if I can provide any other information. Thanks!

**Comment by alexcovington** [comment]
This problem seems to go away when I downgrade from Python version 3.9.5 to 3.7.9.
