### ISSUE TITLE
Remove FailureReporter

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#2017]
As we've moved on to the Azure notification strategy we should remove the FailureReporter code from our pipelines.

```
Traceback (most recent call last):
  File "/datadisks/disk1/work/A6EB0965/p/shared/startup.py", line 116, in runtests
    RunCommand(startup_args, verbose=True).run()
  File "/datadisks/disk1/work/A6EB0965/p/scripts/performance/common.py", line 219, in run
    returncode, quoted_cmdline)
subprocess.CalledProcessError: Command '$ /datadisks/disk1/work/A6EB0965/p/startup/Startup --app-exe dotnet --metric-type ProcessTime --trace-name "SDK Class library Template Build(No Change)_startup" --gui-app false --process-will-exit true --iterations 1 --timeout 600 --warmup true --working-dir app --report-json-path traces/perf-lab-report.json --trace-directory traces --scenario-name "SDK Class library Template Build(No Change)" --app-args build --environment-variables DOTNET_MULTILEVEL_LOOKUP=0' returned non-zero exit status 255.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 18, in <module>
    main()
  File "test.py", line 14, in main
    runner.run()
  File "/datadisks/disk1/work/A6EB0965/p/shared/runner.py", line 222, in run
    startup.runtests(self.traits)
  File "/datadisks/disk1/work/A6EB0965/p/shared/startup.py", line 136, in runtests
    RunCommand(cmdline, verbose=True).run(reporterpath)
  File "/datadisks/disk1/work/A6EB0965/p/scripts/performance/common.py", line 210, in run
    (returncode, quoted_cmdline) = self.__runinternal(working_directory)
  File "/datadisks/disk1/work/A6EB0965/p/scripts/performance/common.py", line 195, in __runinternal
    universal_newlines=True,
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'FailureReporting': 'FailureReporting'`
```

**Comment by Tohron** [comment]
Created https://github.com/dotnet/performance/pull/2019

**Comment by Lxiamail** [comment]
@Tohron is this work done?
