### ISSUE TITLE
MicroBenchmark runs are failing when executing Perf_Regex_Industry_Leipzig tests

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2140]
MicroBenchmark runs are failing when executing Perf_Regex_Industry_Leipzig tests. The specific error is 
```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 21: invalid continuation byte
```
As a part of 
```
[2021/11/18 12:22:02][INFO] // Found 5 benchmarks:
[2021/11/18 12:22:02][INFO] //   Perf_Regex_Industry_Leipzig.Count: Job-RCHHKQ(PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0) [Pattern=(?i)Tom|Sawyer|Huckleberry|Finn, Options=Compiled]
[2021/11/18 12:22:02][INFO] //   Perf_Regex_Industry_Leipzig.Count: Job-RCHHKQ(PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0) [Pattern=Huck[a-zA-Z]+|Saw[a-zA-Z]+, Options=None]
[2021/11/18 12:22:02][INFO] //   Perf_Regex_Industry_Leipzig.Count: Job-RCHHKQ(PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0) [Pattern=Tom.{10,25}river|river.{10,25}Tom, Options=None]
[2021/11/18 12:22:02][INFO] //   Perf_Regex_Industry_Leipzig.Count: Job-RCHHKQ(PowerPlanMode=00000000-0000-0000-0000-000000000000, Arguments=/p:DebugType=portable,-bl:benchmarkdotnet.binlog, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0) [Pattern=Twain, Options=Compiled]
[2021/11/18 12:22:52][INFO] $ popd
Traceback (most recent call last):
  File "C:\h\w\AB8A099E\p\scripts\benchmarks_ci.py", line 250, in <module>
    __main(sys.argv[1:])
  File "C:\h\w\AB8A099E\p\scripts\benchmarks_ci.py", line 226, in __main
    micro_benchmarks.run(
  File "C:\h\w\AB8A099E\p\scripts\micro_benchmarks.py", line 310, in run
    BENCHMARKS_CSPROJ.run(
  File "C:\h\w\AB8A099E\p\scripts\dotnet.py", line 467, in run
    RunCommand(cmdline, verbose=verbose).run(
  File "C:\h\w\AB8A099E\p\scripts\performance\common.py", line 211, in run
    (returncode, quoted_cmdline) = self.__runinternal(working_directory)
  File "C:\h\w\AB8A099E\p\scripts\performance\common.py", line 200, in __runinternal
    for line in iter(proc.stdout.readline, ''):
  File "C:\python3.9.1\lib\codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 78: invalid continuation byte
```

The tests need to be disabled and investigated to figure out why this problem is showing up.

cc @DrewScoggins @stephentoub

**Comment by LoopedBard3** [comment]
Tasks to complete:

- [ ] Disable the test to get the pipelines green again
- [ ] Investigate why this error is showing up in the pipeline but does not seem to be easily reproducible locally
- [ ] Reenable the tests

**Comment by LoopedBard3** [comment]
Note: These tests were recently added in #2125 so a different change is unlikely to be the direct cause of the failure.

**Comment by danmoseley** [comment]
We saw that on the original PR validation and @DrewScoggins believed it was fixed by #2108

It might be from `            "\u221E|\u2713",`

**Comment by LoopedBard3** [comment]
Yea, the error was the same error type that it had fixed, but it seemed to have popped back up with what you mentioned most likely. I think trying to change the encoding similar to utf-16 similar to #2108 may fix the issue, but I have not had a chance to test it yet.
