### ISSUE TITLE
request: skip libgdiplus related tests when the Linux platform does not have libgdiplus installed

### ISSUE THREAD

**Issue by tmds** [dotnet/performance#2156]
Not all flavors of linux come with libgdiplus.

Instead of throwing, can we print a warning and skip the tests instead:

https://github.com/dotnet/performance/blob/b72838ebdd172898a72f2f015ff5384db2c64261/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs#L62-L74

Currently, each time I run the benchmark suite, I comment out the libgdiplus related tests to avoid:
```
libgdiplus is missing, you can install it by running 'apt-get install libgdiplus'
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'libgdiplus' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: liblibgdiplus: cannot open shared object file: No such file or directory
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, IntPtr scan0, IntPtr& bitmap)
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData.CreateTestImage(ImageFormat format) in /home/tmds/repos/jenkins-scripts/ci/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 99
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData..ctor(ImageFormat format) in /home/tmds/repos/jenkins-scripts/ci/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 84
   at System.Drawing.Tests.Perf_Image_Load.CreateTestCases() in /home/tmds/repos/jenkins-scripts/ci/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 54
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Drawing.Tests.Perf_Image_Load.ImageFormats() in /home/tmds/repos/jenkins-scripts/ci/performance/src/benchmarks/micro/libraries/System.Drawing/Perf_Image_Load.cs:line 21
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target, SummaryStyle summaryStyle)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type type, MethodInfo[] benchmarkMethods, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config, Boolean askUserForInput)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /home/tmds/repos/jenkins-scripts/ci/performance/src/benchmarks/micro/Program.cs:line 42
```

cc @adamsitnik

**Comment by adamsitnik** [comment]
> Instead of throwing, can we print a warning and skip the tests instead:

Good idea, it has been a PITA for a long time (#621, #727, #1480).

To make sure that we still run these tests in our lab we can use the following logic to determine if it should fail silently or not:

https://github.com/dotnet/performance/blob/e787033b45462c49e5e65563b37b52ab2f16359e/src/tools/Reporting/Reporting/Reporter.cs#L153

**Comment by tmds** [comment]
@adamsitnik side-question. I'm running the micro suite with .net 7 on a 4-core VM. After almost 3 hours, it is still busy. How long does it take to run the full suite?

If I increase the core count, probably it won't run much faster, will it?

**Comment by adamsitnik** [comment]
> How long does it take to run the full suite?

6-7 hours

> If I increase the core count, probably it won't run much faster, will it?

BDN runs benchmarks sequentially so it won't help.
