### ISSUE TITLE
benchmarks_ci.py crashes with character encoding issue on Czech Windows with Win1250 encoding

### ISSUE THREAD

**Issue by janvorli** [dotnet/performance#2207]
I am unable to run `benchmarks_ci.py` on my private machine with Czech Windows. Running it results in the following error while parsing `dotnet --info` output:
```
[2022/01/10 17:28:00][INFO] $ dotnet --info
Traceback (most recent call last):
File ".\performance\scripts\benchmarks_ci.py", line 253, in <module>
__main(sys.argv[1:])
File ".\performance\scripts\benchmarks_ci.py", line 203, in __main
dotnet.info(verbose=verbose)
File "G:\git\performance\scripts\dotnet.py", line 40, in info
RunCommand(cmdline, verbose=verbose).run()
File "G:\git\performance\scripts\performance\common.py", line 218, in run
(returncode, quoted_cmdline) = self.__runinternal(working_directory)
File "G:\git\performance\scripts\performance\common.py", line 206, in __runinternal
for line in iter(proc.stdout.readline, ''):
File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\codecs.py", line 322, in decode
(result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xec in position 36: invalid continuation byte
```

The output of the `dotnet --info` contains some czech characters. The Windows 1250 is the default encoding on this version of Windows. 
The output of the `dotnet --info` starts like this:
```
G:\git>dotnet --info
Sada .NET SDK (s ohledem na libovolný soubor global.json):
Version: 6.0.100-rc.2.21505.57
Commit: ab39070116



Běhové prostředí:
OS Name: Windows
OS Version: 10.0.19044
OS Platform: Windows
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-rc.2.21505.57\
```

It seems that the issue was introduced by #2108 that seems to assume that Windows always use UTF-8 encoding.

**Comment by janvorli** [comment]
cc: @LoopedBard3, @Tohron

**Comment by LoopedBard3** [comment]
Hello Jan, 

Can you try deleting the change made by #2108 and run the benchmarks_ci.py a few times to see if the issue persists? Specifically, removing the set encoding line in scripts/performance/common.py. 

Thanks,
Parker

**Comment by janvorli** [comment]
@LoopedBard3 I've tried that and it fixed the issue. 
A small correction to what I've said before, the encoding is CP852 in my case, not Win1250.

It seems that a proper fix would be what's suggested here:
https://stackoverflow.com/questions/33283603/python-popen-communicate-str-encodeencoding-utf-8-errors-ignore-cr

**Comment by LoopedBard3** [comment]
Thanks for the SO post! Based on it, could you try running the py file with the encoding='utf-8' added back in and then add errors='replace' similar to what is shown in the SO post?

**Comment by janvorli** [comment]
Wouldn't the errors='replace' just remove the characters that were in a different encoding instead of properly converting them to utf-8?
I've tried this instead which seems to work and also produce correct output of the czech characters to the console:
```python
            with Popen(
                    self.cmdline,
                    stdout=PIPE if should_pipe else DEVNULL,
                    stderr=STDOUT,
            ) as proc:
                if proc.stdout is not None:
                    output, errors = proc.communicate()
                    self.__stdout = StringIO()
                    for line in output.decode('cp852').splitlines():
                        self.__stdout.write(line)
                        line = line.rstrip()
                        getLogger().info(line)
                proc.wait()
                return (proc.returncode, quoted_cmdline)
```
The 'cp852' would somehow need to be extracted to be the encoding used on the current system.

**Comment by LoopedBard3** [comment]
Pretty much for the errors point, setting it to replace would replace unknown characters with ?. Looking into ways to extract the systems encoding, could you try importing sys and running sys.getfilesystemencoding() in python? I am curious as to what it returns on your computer as it returns utf-8 on mine which would stop errors when decoding utf-8 locally.

**Comment by janvorli** [comment]
So, sys.getfilesystemencoding() returns utf-8 too for me. The python doc (https://docs.python.org/3/library/subprocess.html) says though that:
> Changed in version 3.3: When universal_newlines is True, the class uses the encoding locale.getpreferredencoding(False) instead of locale.getpreferredencoding(). See the io.TextIOWrapper class for more information on this change.

The locale.getpreferredencoding(False) returns 'cp1250' in my case. So I've tried to revert my change shared above and just replaced `encoding='utf-8'` by `encoding='cp1250'`. That fixes the crash, but the czech characters logged to the shell are not correct. Only when I replaced it with `encoding='cp852'`, the console output was fully correct. 
The cp852 is a DOS czech code page, the cp1250 is a windows one. In fact, using the cp1250 is the right thing to do, as the textual log file created then contains the correct encoding (opening the log in e.g. notepad shows correct characters). So the problem is really just the stupid command prompt.

@LoopedBard3 What does locale.getpreferredencoding(False) get on your system?

**Comment by LoopedBard3** [comment]
It looks like it locally uses cp1250 for me.

**Comment by janvorli** [comment]
Does it work for you replace `encoding='utf-8'` by `encoding='cp1250'`?

**Comment by LoopedBard3** [comment]
Unfortunately, both of those succeed on my system. I have some other tests running with:
`
                    encoding="locale",
                    errors='namereplace'
`
This should cause the runs to use whatever the local default is for the encoding (https://docs.python.org/3/library/io.html#io.TextIOWrapper) and the errors should cause anything to be replaced with some form of a value that maps to the errored value.  If you have a chance and can try running this to see if it works as expected on your system it would be helpful for making sure this wholly fixes the issue.

**Comment by janvorli** [comment]
encoding="locale" fails with 
`LookupError: unknown encoding: locale`
