### ISSUE TITLE
OpenSSL error on Ubuntu running HandshakeRSA1024CertAsync

### ISSUE THREAD

**Issue by danmoseley** [dotnet/performance#2227]
```c#
        [Benchmark]
        [ArgumentsSource(nameof(TlsProtocols))]
        public Task HandshakeRSA1024CertAsync(SslProtocols protocol) => SslStreamTests.HandshakeAsync(SslStreamTests._rsa1024Cert, protocol);
```
failed on Ubuntu 20.04 WSL2 with 
```
[2022/01/31 16:37:41][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/01/31 16:37:41][INFO]  ---> System.Security.Authentication.AuthenticationException: Authentication failed, see inner exception.
[2022/01/31 16:37:41][INFO]  ---> Interop+OpenSsl+SslException: SSL Handshake failed with OpenSSL error - SSL_ERROR_SSL.
[2022/01/31 16:37:41][INFO]  ---> Interop+Crypto+OpenSslCryptographicException: error:1409442E:SSL routines:ssl3_read_bytes:tlsv1 alert protocol version
[2022/01/31 16:37:41][INFO]    --- End of inner exception stack trace ---
[2022/01/31 16:37:41][INFO]    at Interop.OpenSsl.DoSslHandshake(SafeSslHandle context, ReadOnlySpan`1 input, Byte[]& sendBuf, Int32& sendCount)
[2022/01/31 16:37:41][INFO]    at System.Net.Security.SslStreamPal.HandshakeInternal(SafeFreeCredentials credential, SafeDeleteSslContext& context, ReadOnlySpan`1 inputBuffer, Byte[]& outputBuffer, SslAuthenticationOptions sslAuthenticationOptions)
[2022/01/31 16:37:41][INFO]    --- End of inner exception stack trace ---
[2022/01/31 16:37:41][INFO]    at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
[2022/01/31 16:37:41][INFO]    at System.Net.Security.Tests.SslStreamTests.HandshakeAsync(X509Certificate certificate, SslProtocols sslProtocol) in /home/dan/git/performance/src/benchmarks/micro/libraries/System.Net.Security/SslStreamTests.cs:line 174
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_2347.<.ctor>b__3_2(SslProtocols arg0) in /home/dan/git/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/088c2f80-080b-42d8-8622-007ad4450acf/088c2f80-080b-42d8-8622-007ad4450acf.notcs:line 1730064
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_2347.WorkloadActionNoUnroll(Int64 invokeCount) in /home/dan/git/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/088c2f80-080b-42d8-8622-007ad4450acf/088c2f80-080b-42d8-8622-007ad4450acf.notcs:line 1730717
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_2347.Run(IHost host, String benchmarkName) in /home/dan/git/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/088c2f80-080b-42d8-8622-007ad4450acf/088c2f80-080b-42d8-8622-007ad4450acf.notcs:line 1730043
[2022/01/31 16:37:41][INFO]    --- End of inner exception stack trace ---
[2022/01/31 16:37:41][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[2022/01/31 16:37:41][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022/01/31 16:37:41][INFO]    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in /home/dan/git/performance/artifacts/bin/MicroBenchmarks/Release/net7.0/088c2f80-080b-42d8-8622-007ad4450acf/088c2f80-080b-42d8-8622-007ad4450acf.notcs:line 4060
[2022/01/31 16:37:41][INFO] // AfterAll
[2022/01/31 16:37:41][INFO] // Benchmark Process 15041 has exited with code 255.
```
the generated code is
```c#
          workloadDelegate = ( arg0) => { HandshakeRSA1024CertAsync( arg0).GetAwaiter().GetResult(); };
            __argField0 = (System.Security.Authentication.SslProtocols)(3072);
```
which is SslProtocols.Tls12 .

@wfurt do you know what this means? The error is not the best 😃 

cc @adamsitnik this broke my run on Ubuntu.

**Comment by danmoseley** [comment]
This is with Ubuntu image direct from the Windows store, ie., I didn't update OpenSSL or change any settings.

**Comment by wfurt** [comment]
Hmm. something similar was reported while back. I suspect this may be some kind of default setting about weak key. 
Did the other tests finished? 
We may need to look into making some test conditional .. like we do for runtime tests.

**Comment by wfurt** [comment]
I played with this more and it fails even with plain openssl
```
140571708564800:error:140AB18F:SSL routines:SSL_CTX_use_certificate:ee key too small:../ssl/ssl_rsa.c:310:
```

creating X509Certificate still works but it fails when we try to authenticate as Server. I'm wondering if we should try to wrestle openssl to accept certificates we give it @bartonjs 

Alternatively, we can try to make the test optional or simply remove benchmark for (now) weak key leaving RSA2048 and RSA4096.

**Comment by bartonjs** [comment]
I think this is one of those "the system config says to have a minimum security policy here", so the small key is being rejected... and generally we don't fight system policies too much.

As a benchmark, I'd just remove it.  For a unit test, I'd waffle on removing it or detecting it as an acceptable failure.

2048 is really what people ought to be doing these days, so that's probably the one worth measuring the most.

**Comment by wfurt** [comment]
OK.  I'll remove the test and I'll verify we throw something reasonable in SslStream.
