### ISSUE TITLE
PR Checks into Optimization repo are failing

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2297]
Bot updates into the optimization repository are failing during the training step:
```
Unhandled exception. System.Exception: Failed to download https://dotnetcli.azureedge.net/dotnet/Sdk/6.0.104-servicing.22158.14/dotnet-sdk-pgo-6.0.104-servicing.22158.14-linux-x64.tar.gz.  Status code: NotFound
   at Microsoft.DotNet.Optimization.Utilities.DownloadFile(String sourceUrl, String destPath) in /_/src/core/Utilities.cs:line 211
   at Microsoft.DotNet.Optimization.NetCoreApp.SDK.Install(OSPlatform os, Architecture architecture, String channel, String version, String installDir, Boolean usePgoSdk) in /_/src/products/netcoreapp/SDK.cs:line 40
   at Microsoft.DotNet.Optimization.NetCoreApp.CoreCLR.Setup(OptimizationTool optTool) in /_/src/products/netcoreapp/CoreCLR.cs:line 63
   at Microsoft.DotNet.Optimization.TrainingJob.GenerateTrainingData(String layoutDirectory) in /_/src/core/TrainingJob.cs:line 123
   at Microsoft.DotNet.Optimization.TrainingJob.Execute() in /_/src/core/TrainingJob.cs:line 46
   at Microsoft.DotNet.Optimization.AutomatedOptimizationJob.processJob(Job job, Action`1 onSuccess) in /_/src/jobs/AutomatedOptimizationJob.cs:line 21
   at Microsoft.DotNet.Optimization.AutomatedOptimizationJob.runJobs() in /_/src/jobs/AutomatedOptimizationJob.cs:line 79
   at Microsoft.DotNet.Optimization.AutomatedOptimizationJob.Execute() in /_/src/jobs/AutomatedOptimizationJob.cs:line 32
   at Microsoft.DotNet.Optimization.Program.Main(String[] args) in /_/src/Program.cs:line 28
./train.sh: line 77:   724 Aborted                 (core dumped) $dotnetCmd $currentDir/artifacts/bin/optimization/$buildConfiguration/net6.0/optimization.dll --output-directory="$outputDirectory" --train $jobs $rerunscenarios
```

**Comment by LoopedBard3** [comment]
CI's appear to have been fixed.
