### ISSUE TITLE
Performance-ci  Ubuntu x64 scenarios and sdk_scenarios are failing with Number Format Exception

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2298]
The Ubuntu x64 scenarios and sdk_scenarios are failing while parsing the output files due to a FormatException seemingly hit while reading attempting to read a number. There are also some earlier errors during the LTTng install missing step. A run with this occuring is https://dev.azure.com/dnceng/public/_build/results?buildId=1653633&view=results and the exception is as follows:
```
[2022/03/09 12:23:55][INFO] Parsing traces/Startup_-_Static_VB_Console_Template_-_FDD_Publish_startup.trace.zip
[2022/03/09 12:23:55][INFO] Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/03/09 12:23:55][INFO]  ---> System.FormatException: Input string was not in a correct format.
[2022/03/09 12:23:55][INFO]    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
[2022/03/09 12:23:55][INFO]    at System.Int32.Parse(String s)
[2022/03/09 12:23:55][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfPropertyBag.GetIntOrNull(String name)
[2022/03/09 12:23:55][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfStruct..ctor(CtfPropertyBag props, CtfField[] fields)
[2022/03/09 12:23:55][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfMetadata.Load(CtfMetadataParser parser)
[2022/03/09 12:23:55][INFO]    at Microsoft.Diagnostics.Tracing.CtfTraceEventSource..ctor(String fileName)
[2022/03/09 12:23:55][INFO]    at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.GetDispatcherFromFileName(String traceFileName, TraceEventDispatcherOptions options)
[2022/03/09 12:23:55][INFO]    at ScenarioMeasurement.TraceSourceManager..ctor(String fileName) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TraceSourceManager.cs:line 34
[2022/03/09 12:23:55][INFO]    at ScenarioMeasurement.TimeToMainParser.Parse(String mergeTraceFile, String processName, IList`1 pids, String commandLine) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TimeToMainParser.cs:line 29
[2022/03/09 12:23:55][INFO]    at ScenarioMeasurement.Startup.Main(String appExe, MetricType metricType, String scenarioName, String traceName, Boolean processWillExit, Int32 iterations, String iterationSetup, String setupArgs, String iterationCleanup, String cleanupArgs, Int32 timeout, Int32 measurementDelay, String appArgs, String logFileName, String workingDir, Boolean warmup, Boolean guiApp, Boolean skipProfileIteration, String reportJsonPath, String traceDirectory, String environmentVariables, String innerLoopCommand, String innerLoopCommandArgs, Boolean runWithoutExit, Int32 hotReloadIters, Boolean skipMeasurementIteration, Boolean parseOnly) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/Startup.cs:line 321
[2022/03/09 12:23:55][INFO]    --- End of inner exception stack trace ---
[2022/03/09 12:23:55][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[2022/03/09 12:23:55][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Invocation.ModelBindingCommandHandler.InvokeAsync(InvocationContext context)
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseErrorReporting>b__19_0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass14_0.<<UseHelp>b__0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass21_0.<<UseTypoCorrections>b__0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__20_0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseParseDirective>b__18_0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseDebugDirective>b__10_0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__9_0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass5_0.<<ConfigureConsole>b__0>d.MoveNext()
[2022/03/09 12:23:55][INFO] --- End of stack trace from previous location ---
[2022/03/09 12:23:55][INFO]    at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseExceptionHandler>b__0>d.MoveNext()
[2022/03/09 12:23:55][ERROR] Process exited with status 1
[2022/03/09 12:23:55][INFO] Run failure registered
Traceback (most recent call last):
  File "test.py", line 13, in <module>
    Runner(traits).run()
  File "/datadisks/disk1/work/9E1B08C6/p/shared/runner.py", line 209, in run
    startup.runtests(self.traits)
  File "/datadisks/disk1/work/9E1B08C6/p/shared/startup.py", line 150, in runtests
    RunCommand(startup_args, verbose=True).run()
  File "/datadisks/disk1/work/9E1B08C6/p/scripts/performance/common.py", line 227, in run
    returncode, quoted_cmdline)
```

**Comment by LoopedBard3** [comment]
The ubuntu scenarios seem to be in a fixed state now. There are some windows errors but they appear to be unrelated: https://github.com/dotnet/performance/issues/2332
