### ISSUE TITLE
performance And performance-ci Ubuntu Runs Failing: TraceEventDispatcher File Name Invalid

### ISSUE THREAD

**Issue by Tohron** [dotnet/performance#2310]
Ubuntu runs in pipelines such as
https://dev.azure.com/dnceng/public/_build/results?buildId=1666412&view=logs&j=eb966026-ffac-5e5d-c386-bb16f129c37d&t=93c54018-703f-56cb-c07d-6a66042c3bca
and
https://dev.azure.com/dnceng/internal/_build/results?buildId=1666419&view=logs&j=9d3763e3-464f-5ce4-a590-b3a4c86731a8&t=e25af830-d112-5cfc-25b3-2b03b2d7aa7c
are failing with the message
```
[2022/03/16 23:21:30][INFO] Parsing traces/Startup_-_New_Console_Template_-_FDD_Publish_startup.trace.zip
[2022/03/16 23:21:30][INFO] Unhandled exception: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/03/16 23:21:30][INFO]  ---> System.FormatException: Input string was not in a correct format.
[2022/03/16 23:21:30][INFO]    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
[2022/03/16 23:21:30][INFO]    at System.Int32.Parse(String s)
[2022/03/16 23:21:30][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfPropertyBag.GetIntOrNull(String name)
[2022/03/16 23:21:30][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfStruct..ctor(CtfPropertyBag props, CtfField[] fields)
[2022/03/16 23:21:30][INFO]    at Microsoft.Diagnostics.Tracing.Ctf.CtfMetadata.Load(CtfMetadataParser parser)
[2022/03/16 23:21:30][INFO]    at Microsoft.Diagnostics.Tracing.CtfTraceEventSource..ctor(String fileName)
[2022/03/16 23:21:30][INFO]    at Microsoft.Diagnostics.Tracing.TraceEventDispatcher.GetDispatcherFromFileName(String traceFileName, TraceEventDispatcherOptions options)
[2022/03/16 23:21:30][INFO]    at ScenarioMeasurement.TraceSourceManager..ctor(String fileName) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TraceSourceManager.cs:line 34
[2022/03/16 23:21:30][INFO]    at ScenarioMeasurement.TimeToMainParser.Parse(String mergeTraceFile, String processName, IList`1 pids, String commandLine) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/TimeToMainParser.cs:line 29
[2022/03/16 23:21:30][INFO]    at ScenarioMeasurement.Startup.Main(String appExe, MetricType metricType, String scenarioName, String traceName, Boolean processWillExit, Int32 iterations, String iterationSetup, String setupArgs, String iterationCleanup, String cleanupArgs, Int32 timeout, Int32 measurementDelay, String appArgs, String logFileName, String workingDir, Boolean warmup, Boolean guiApp, Boolean skipProfileIteration, String reportJsonPath, String traceDirectory, String environmentVariables, String innerLoopCommand, String innerLoopCommandArgs, Boolean runWithoutExit, Int32 hotReloadIters, Boolean skipMeasurementIteration, Boolean parseOnly) in /__w/1/s/src/tools/ScenarioMeasurement/Startup/Startup.cs:line 321
```

Looking at TraceEventManager.cs, it appears the line
Source = TraceEventDispatcher.GetDispatcherFromFileName(fileName);
fails due to fileName being invalid.

**Comment by LoopedBard3** [comment]
Performance runs are running successfully now, closing for cleanup.
