### ISSUE TITLE
Maui Perf: iOS Startup Scenarios are failing

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2392]
The Maui iOS Startup Scenarios are failing. It seems they started failing around 4/16 as that is the latest data on Power BI. This failure was not bubbled up into the azure devops view of the runs which had them showing green. The error section is as follows:
```
[2022/04/22 07:03:09][INFO] [07:03:09] dbug: Process mlaunch exited with 0
[2022/04/22 07:03:09][INFO] [07:03:09] info: Application 'MauiTesting' was installed successfully on 'PERFIOS-01'
[2022/04/22 07:03:09][INFO] [07:03:09] dbug: Saving diagnostics data to '/tmp/helix/working/A9BF09B2/w/ADC9098A/e/diagnostics.json'
[2022/04/22 07:03:09][INFO] XHarness exit code: 0
[2022/04/22 07:03:09][INFO] Completed install.
[2022/04/22 07:03:09][INFO] Waiting 10 secs to ensure we're not getting confused with previous app run.
[2022/04/22 07:03:19][INFO] Collect startup data for iteration 0.
[2022/04/22 07:03:19][INFO] $ dotnet exec /tmp/helix/working/A9BF09B2/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.22214.2/tools/net6.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdevbundleid=net.dot.mauitesting
[2022/04/22 07:05:19][INFO] Killing process 4298 as it was cancelled
[2022/04/22 07:05:19][ERROR] Process exited with status 70
Traceback (most recent call last):
  File "test.py", line 12, in <module>
    Runner(traits).run()
  File "/tmp/helix/working/A9BF09B2/w/ADC9098A/u/shared/runner.py", line 685, in run
    runCmdCommand.run()
  File "/tmp/helix/working/A9BF09B2/w/ADC9098A/u/scripts/performance/common.py", line 241, in run
    raise CalledProcessError(
subprocess.CalledProcessError: Command '$ dotnet exec /tmp/helix/working/A9BF09B2/p/microsoft.dotnet.xharness.cli/1.0.0-prerelease.22214.2/tools/net6.0/any/Microsoft.DotNet.XHarness.CLI.dll apple mlaunch -- --launchdevbundleid=net.dot.mauitesting' returned non-zero exit status 70.
```
It seems that the mlaunch command is failing to launch the app on the iOS devices.

**Comment by LoopedBard3** [comment]
Testing on one of the devices used, one thing that sticks out from the iOS device is a 'terminate_with_reason() failed with error: -1' from console.app.

**Comment by LoopedBard3** [comment]
Looking further, the request to start the app seems to be going through with Springboard receiving the app open request for the maui apps, and then nothing seems to happen after that.

**Comment by SamMonoRT** [comment]
Do we still need to manually update the MAUI sdk version like (https://github.com/dotnet/runtime/pull/66671)  I believe there was a Preview 4 snap around the 18th

**Comment by LoopedBard3** [comment]
It looks like the Version specified in the Maui Versions.props is still 6.0.3xx https://github.com/dotnet/maui/blob/main/eng/Versions.props#L4 and the build itself does not seem to be failing, but something that I may try depending on what I hear back from people more familiar with the iOS space.

**Comment by LoopedBard3** [comment]
This appears to be fixed after device restart. Closing for now.
