### ISSUE TITLE
Windows micro runs in performance-ci occassionally failing with OutOfMemoryException

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2507]
Windows is failing with OutOfMemoryException a ways into BDN microbenchmark testing. This seems to be flaky, not failing in all BDN test partitions. An example can be found here: https://dev.azure.com/dnceng/public/_build/results?buildId=1838682&view=results. The OOM exception seems to then result in another error, the chain of these errors is:
```
[2022/06/22 12:35:38][INFO] // Benchmark: Perf_Regex_Industry_SliceSlice.Count: Job-GHEJAQ(PowerPlanMode=00000000-0000-0000-0000-000000000000, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=3, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0) [Options=NonBacktracking]
[2022/06/22 12:35:38][INFO] // *** Execute ***
[2022/06/22 12:35:38][INFO] // Launch: 1 / 1
[2022/06/22 12:35:38][INFO] // Execute: dotnet dab32b46-672a-4e01-9ab8-a6ea48ed4005.dll --benchmarkName "System.Text.RegularExpressions.Tests.Perf_Regex_Industry_SliceSlice.Count(Options: NonBacktracking)" --job "PowerPlanMode=00000000-0000-0000-0000-000000000000, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=3, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0" --benchmarkId 875 in C:\h\w\B72909A2\p\artifacts\bin\MicroBenchmarks\Release\net7.0\dab32b46-672a-4e01-9ab8-a6ea48ed4005\bin\Release\net7.0
[2022/06/22 12:35:39][INFO] // BeforeAnythingElse
[2022/06/22 12:35:39][INFO] 
[2022/06/22 12:35:39][INFO] // Benchmark Process Environment Information:
[2022/06/22 12:35:39][INFO] // Runtime=.NET 7.0.0 (7.0.22.31201), X86 RyuJIT
[2022/06/22 12:35:39][INFO] // GC=Concurrent Workstation
[2022/06/22 12:35:39][INFO] // Job: Job-LKQSCT(PowerPlanMode=00000000-0000-0000-0000-000000000000, InvocationCount=1, IterationCount=1, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=3, RunStrategy=ColdStart, UnrollFactor=1, WarmupCount=0)
[2022/06/22 12:35:39][INFO] 
[2022/06/22 12:35:47][INFO] // BeforeActualRun
[2022/06/22 12:35:53][INFO] 
[2022/06/22 12:35:53][INFO] OutOfMemoryException!
[2022/06/22 12:35:53][INFO] BenchmarkDotNet continues to run additional iterations until desired accuracy level is achieved. It's possible only if the benchmark method doesn't have any side-effects.
[2022/06/22 12:35:53][INFO] If your benchmark allocates memory and keeps it alive, you are creating a memory leak.
[2022/06/22 12:35:53][INFO] You should redesign your benchmark and remove the side-effects. You can use `OperationsPerInvoke`, `IterationSetup` and `IterationCleanup` to do that.
[2022/06/22 12:35:53][INFO] 
[2022/06/22 12:35:53][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2022/06/22 12:35:53][INFO]  ---> System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
[2022/06/22 12:35:53][INFO]    at System.Collections.Generic.Dictionary`2.Resize(Int32 newSize, Boolean forceNewHashCodes)
[2022/06/22 12:35:53][INFO]    at System.Collections.Generic.Dictionary`2.Resize()
[2022/06/22 12:35:53][INFO]    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexNode`1.Subsumes(SymbolicRegexNode`1 other, Int32 depth)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexNode`1.CreateAlternate(SymbolicRegexBuilder`1 builder, SymbolicRegexNode`1 left, SymbolicRegexNode`1 right, Boolean deduplicated, Boolean hintRightLikelySubsumes)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexNode`1.CreateDerivative(TSet elem, UInt32 context)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexNode`1.CreateDerivativeWrapper(TSet elem, UInt32 context)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.DfaMatchingState`1.Next(TSet minterm)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexBuilder`1.TryCreateNewTransition(DfaMatchingState`1 sourceState, Int32 mintermId, Int32 offset, Boolean checkThreshold, DfaMatchingState`1& nextState)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexMatcher`1.FindEndPositionDeltas[TStateHandler,TFindOptimizationsHandler,TNullabilityHandler](SymbolicRegexBuilder`1 builder, ReadOnlySpan`1 input, RegexRunnerMode mode, Int32& posRef, CurrentState& stateRef, Int32& endPosRef, Int32& endStateIdRef, Int32& initialStatePosRef, Int32& initialStatePosCandidateRef)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexMatcher`1.FindEndPosition[TFindOptimizationsHandler,TNullabilityHandler](ReadOnlySpan`1 input, Int32 pos, Int64 timeoutOccursAt, RegexRunnerMode mode, Int32& initialStatePos, Int32& matchLength, PerThreadData perThreadData)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexMatcher`1.FindMatch(RegexRunnerMode mode, ReadOnlySpan`1 input, Int32 startat, PerThreadData perThreadData)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Symbolic.SymbolicRegexRunnerFactory.Runner`1.Scan(ReadOnlySpan`1 text)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Regex.RunAllMatchesWithCallback[TState](String inputString, ReadOnlySpan`1 inputSpan, Int32 startat, TState& state, MatchCallback`1 callback, RegexRunnerMode mode, Boolean reuseMatchObject)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Regex.Count(String input)
[2022/06/22 12:35:53][INFO]    at System.Text.RegularExpressions.Tests.Perf_Regex_Industry_SliceSlice.Count() in C:\h\w\B72909A2\p\src\benchmarks\micro\libraries\System.Text.RegularExpressions\Perf.Regex.Industry.cs:line 118
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_875.WorkloadActionUnroll(Int64 invokeCount) in C:\h\w\B72909A2\p\artifacts\bin\MicroBenchmarks\Release\net7.0\dab32b46-672a-4e01-9ab8-a6ea48ed4005\dab32b46-672a-4e01-9ab8-a6ea48ed4005.notcs:line 161169
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Engines.EngineActualStage.RunSpecific(Int64 invokeCount, IterationMode iterationMode, Int32 iterationCount, Int32 unrollFactor)
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Engines.EngineActualStage.Run(Int64 invokeCount, IterationMode iterationMode, Boolean runAuto, Int32 unrollFactor, Boolean forceSpecific)
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Engines.EngineActualStage.RunWorkload(Int64 invokeCount, Int32 unrollFactor, Boolean forceSpecific)
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Engines.Engine.Run()
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_875.Run(IHost host, String benchmarkName) in C:\h\w\B72909A2\p\artifacts\bin\MicroBenchmarks\Release\net7.0\dab32b46-672a-4e01-9ab8-a6ea48ed4005\dab32b46-672a-4e01-9ab8-a6ea48ed4005.notcs:line 161068
[2022/06/22 12:35:53][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[2022/06/22 12:35:53][INFO]    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[2022/06/22 12:35:53][INFO]    --- End of inner exception stack trace ---
[2022/06/22 12:35:53][INFO]    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[2022/06/22 12:35:53][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022/06/22 12:35:53][INFO]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
[2022/06/22 12:35:53][INFO]    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\h\w\B72909A2\p\artifacts\bin\MicroBenchmarks\Release\net7.0\dab32b46-672a-4e01-9ab8-a6ea48ed4005\dab32b46-672a-4e01-9ab8-a6ea48ed4005.notcs:line 58
[2022/06/22 12:35:53][INFO] // AfterAll
```

**Comment by adamsitnik** [comment]
@stephentoub is it expected that `System.Text.RegularExpressions.Regex.Count` can allocate enough memory to OOM?

**Comment by stephentoub** [comment]
This isn't "Count"-specific. This is the NonBacktracking engine lazily expanding its DFA.

Do you have a dump? A repro?

cc: @joperezr, @olsaarik

**Comment by adamsitnik** [comment]
I don't think that we collect dumps for the failed benchmark runs, but the benchmark can be run locally with:

```cmd
git clone https://github.com/dotnet/performance.git
cd performance
py .\scripts\benchmarks_ci.py -f net7.0 --filter System.Text.RegularExpressions.Tests.Perf_Regex_Industry_SliceSlice.Count
```
