### ISSUE TITLE
Python script logging errors when running System.Tests.Perf_String.Trim*

### ISSUE THREAD

**Issue by L2** [dotnet/performance#2779]
Python version: `3.9.13`
Performance repo at the latest commit: `def4ce245230bb9c71`

Run command: `python3 .\scripts\benchmarks_ci.py --architecture x64 -c Release -f net7.0 --filter System.Tests.Perf_String.Trim*`

```
...
...
[2022/12/08 11:02:27][INFO] // **************************
[2022/12/08 11:02:27][INFO] // Benchmark: Perf_String.Trim_CharArr: Job-BWWQRX(PowerPlanMode=00000000-0000-0000-0000-000000000000, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1) [s= Te st  , c=Char[2]]
[2022/12/08 11:02:27][INFO] // *** Execute ***
[2022/12/08 11:02:27][INFO] // Launch: 1 / 1
[2022/12/08 11:02:27][INFO] // Execute: dotnet 9270c228-7863-42f3-9e75-28ded3d409bb.dll --anonymousPipes 2472 2480 --benchmarkName "System.Tests.Perf_String.Trim_CharArr(s: \" Te st  \", c: [' ', ' '])" --job "PowerPlanMode=00000000-0000-0000-0000-000000000000, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1" --benchmarkId 0 in D:\mw\W221206\test1\artifacts\bin\MicroBenchmarks\Release\net7.0\9270c228-7863-42f3-9e75-28ded3d409bb\bin\Release\net7.0
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\logging\__init__.py", line 1086, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.3568.0_x64__qbz5n2kfra8p0\lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\u2005' in position 197: character maps to <undefined>
Call stack:
  File "D:\mw\W221206\test1\scripts\benchmarks_ci.py", line 326, in <module>
    __main(sys.argv[1:])
  File "D:\mw\W221206\test1\scripts\benchmarks_ci.py", line 289, in __main
    is_success = micro_benchmarks.run(
  File "D:\mw\W221206\test1\scripts\micro_benchmarks.py", line 361, in run
    status = BENCHMARKS_CSPROJ.run(
  File "D:\mw\W221206\test1\scripts\dotnet.py", line 500, in run
    return RunCommand(cmdline, success_exit_codes, verbose=verbose).run(
  File "D:\mw\W221206\test1\scripts\performance\common.py", line 242, in run
    (returncode, quoted_cmdline) = self.__runinternal(working_directory)
  File "D:\mw\W221206\test1\scripts\performance\common.py", line 233, in __runinternal
    getLogger().info(line)
Message: '// Execute: dotnet 9270c228-7863-42f3-9e75-28ded3d409bb.dll --anonymousPipes 2472 2480 --benchmarkName "System.Tests.Perf_String.Trim_CharArr(s: \\" Te st  \\", c: [\' \', \'\u2005\'])" --job "PowerPlanMode=00000000-0000-0000-0000-000000000000, IterationTime=250.0000 ms, MaxIterationCount=20, MinIterationCount=15, WarmupCount=1" --benchmarkId 0 in D:\\mw\\W221206\\test1\\artifacts\\bin\\MicroBenchmarks\\Release\\net7.0\\9270c228-7863-42f3-9e75-28ded3d409bb\\bin\\Release\\net7.0'
Arguments: ()
[2022/12/08 11:02:27][INFO] // BeforeAnythingElse
[2022/12/08 11:02:27][INFO]
[2022/12/08 11:02:27][INFO] // Benchmark Process Environment Information:
[2022/12/08 11:02:27][INFO] // Runtime=.NET 7.0.0 (7.0.22.51805), X64 RyuJIT AVX2
[2022/12/08 11:02:27][INFO] // GC=Concurrent Workstation
...
...
```

The benchmark appears to run after this and outputs results, but not sure how this error affects things. Happens for a few benchmarks in the `System.Tests.Perf_String.Trim*` subset.

Thanks

**Comment by caaavik-msft** [comment]
Thanks for reporting this! This should be fixed by the above PR
