### ISSUE TITLE
Performance-ci micro runs failing due to BinaryFormatter

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#2971]
Failure:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2023/04/18 16:39:57][INFO]  ---> System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
[2023/04/18 16:39:57][INFO]    at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(Stream serializationStream, Object graph)
[2023/04/18 16:39:57][INFO]    at MicroBenchmarks.Serializers.Binary_FromStream`1.SetupBinaryFormatter() in C:\h\w\A0730898\p\src\benchmarks\micro\Serializers\Binary_FromStream.cs:line 35
[2023/04/18 16:39:57][INFO]    at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
[2023/04/18 16:39:57][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_46.Run(IHost host, String benchmarkName) in C:\h\w\A0730898\p\artifacts\bin\MicroBenchmarks\Release\net8.0\9b5f3628-a303-4f7c-8056-8ddbedd2a172\9b5f3628-a303-4f7c-8056-8ddbedd2a172.notcs:line 8562
[2023/04/18 16:39:57][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[2023/04/18 16:39:57][INFO]    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[2023/04/18 16:39:57][INFO]    --- End of inner exception stack trace ---
[2023/04/18 16:39:57][INFO]    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[2023/04/18 16:39:57][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2023/04/18 16:39:57][INFO]    at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
[2023/04/18 16:39:57][INFO]    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in C:\h\w\A0730898\p\artifacts\bin\MicroBenchmarks\Release\net8.0\9b5f3628-a303-4f7c-8056-8ddbedd2a172\9b5f3628-a303-4f7c-8056-8ddbedd2a172.notcs:line 57
[2023/04/18 16:39:57][INFO] // AfterAll
```

**Comment by cincuranet** [comment]
@GrabYourPitchforks Is it OK to _ifdef_ only for .NET 7 and lower? Or should the compatibility switch be set and keep benchmarking even on .NET 8?

**Comment by GrabYourPitchforks** [comment]
Responded offline. For non-production code (like benchmarks) it's totally fine to re-enable this, especially since we're still interested in capturing any unintentional breaks. Come .NET 9, when it's properly removed from the product, the benchmarks will also go away.
