### ISSUE TITLE
Scenarios failing on Windows

### ISSUE THREAD

**Issue by adamsitnik** [dotnet/performance#3037]
The scenarios started failing and are blocking the new microbenchmarks PRs (nothing urgent, just creating issue so it's not missed).

From a sample [log file](https://helixre107v0xdeko0k025g8.blob.core.windows.net/dotnet-performance-refs-pull-2926-merge-618b62c7b3014400ba/Startup%20-%20WinForms%20Large%20-%20FDD%20Publish/1/console.d8856d0e.log?helixlogtype=result)

```log
C:\h\w\A8A2098D\w\B976099E\e>py -3 test.py startup --scenario-name "Startup - WinForms Large - FDD Publish" 
[2023/05/23 06:58:59][INFO] ----------------------------------------------
[2023/05/23 06:58:59][INFO] Initializing logger 2023-05-23 06:58:59.607474
[2023/05/23 06:58:59][INFO] ----------------------------------------------
[2023/05/23 06:58:59][INFO] $ C:\h\w\A8A2098D\p\startup\Startup.exe --app-exe pub\WinformsNetCorePerfApp1.exe --metric-type GenericStartup --trace-name "Startup - WinForms Large - FDD Publish_startup" --gui-app true --process-will-exit false --iterations 1 --timeout 30 --warmup true --working-dir C:\h\w\A8A2098D\w\B976099E\e --report-json-path traces\perf-lab-report.json --trace-directory traces --scenario-name "Startup - WinForms Large - FDD Publish" --measurement-delay 6 --run-without-exit false
[2023/05/23 06:59:00][INFO] Running pub\WinformsNetCorePerfApp1.exe (args: "")
[2023/05/23 06:59:00][INFO] Working Directory: C:\h\w\A8A2098D\w\B976099E\e
[2023/05/23 06:59:00][INFO] Iteration set up:  (args: )
[2023/05/23 06:59:00][INFO] Iteration clean up:  (args: )
[2023/05/23 06:59:00][INFO] =============== Warm up ================
[2023/05/23 06:59:00][INFO] ***Test***
[2023/05/23 06:59:14][INFO] Process 8352 failed to run. Result: CloseFailed
[2023/05/23 06:59:14][ERROR] Process exited with status 4294967295
[2023/05/23 06:59:14][INFO] Run failure registered
Traceback (most recent call last):
  File "C:\h\w\A8A2098D\w\B976099E\e\test.py", line 22, in <module>
    main()
  File "C:\h\w\A8A2098D\w\B976099E\e\test.py", line 18, in main
    runner.run()
  File "C:\h\w\A8A2098D\p\shared\runner.py", line 261, in run
    startup.runtests(self.traits)
  File "C:\h\w\A8A2098D\p\shared\startup.py", line 152, in runtests
    RunCommand(startup_args, verbose=True).run()
  File "C:\h\w\A8A2098D\p\scripts\performance\common.py", line 280, in run
    raise CalledProcessError(
subprocess.CalledProcessError: Command '$ C:\h\w\A8A2098D\p\startup\Startup.exe --app-exe pub\WinformsNetCorePerfApp1.exe --metric-type GenericStartup --trace-name "Startup - WinForms Large - FDD Publish_startup" --gui-app true --process-will-exit false --iterations 1 --timeout 30 --warmup true --working-dir C:\h\w\A8A2098D\w\B976099E\e --report-json-path traces\perf-lab-report.json --trace-directory traces --scenario-name "Startup - WinForms Large - FDD Publish" --measurement-delay 6 --run-without-exit false' returned non-zero exit status 4294967295.
```

**Comment by LoopedBard3** [comment]
I took a look into this locally and am getting a popup that expands on the error:
```
System.NotSupportedException: BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information.
   at System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(Stream serializationStream)
   at System.Resources.Extensions.DeserializingResourceReader.DeserializeObject(Int32 typeIndex)
   at System.Resources.Extensions.DeserializingResourceReader._LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObjectV2(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.DeserializingResourceReader.LoadObject(Int32 pos, ResourceTypeCode& typeCode)
   at System.Resources.Extensions.RuntimeResourceSet.ReadValue(DeserializingResourceReader reader, Int32 dataPos, Boolean isString, ResourceLocator& locator)
   at System.Resources.Extensions.RuntimeResourceSet.GetObject(String key, Boolean ignoreCase, Boolean isString)
   at System.Resources.ResourceManager.GetObject(String name, CultureInfo culture, Boolean wrapUnmanagedMemStream)
   at WinformsNetCorePerfApp1.Form3.InitializeComponent() in C:\Users\parkerbibus\Desktop\performance\src\scenarios\windowsformslarge\app\Form3.Designer.cs:line 263
   at WinformsNetCorePerfApp1.Form3..ctor() in C:\Users\parkerbibus\Desktop\performance\src\scenarios\windowsformslarge\app\Form3.cs:line 15
   at WinformsNetCorePerfApp1.WinformsNetCorePerfApp1.WinformsNetCorePerfApp1_Load(Object sender, EventArgs e) in C:\Users\parkerbibus\Desktop\performance\src\scenarios\windowsformslarge\app\WinformsNetCorePerfApp1.cs:line 33
   at System.Windows.Forms.Form.OnLoad(EventArgs e)
   at System.Windows.Forms.Control.CreateControl(Boolean ignoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(HWND hWnd, WM msg, WPARAM wparam, LPARAM lparam)

```

**Comment by LoopedBard3** [comment]
Found issues in the winforms repos already tracking this and like issues: https://github.com/dotnet/winforms/issues/9110 and https://github.com/dotnet/winforms/issues/6267
