### ISSUE TITLE
CscBench.DatflowTest reports 0ns

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#3095]
https://pvscmdupload.blob.core.windows.net/reports/allTestHistory/refs/heads/main_x64_Windows%2010.0.18362/CscBench.DatflowTest.html

**Comment by cincuranet** [comment]
The benchmark is failing with:

```text
[2023/07/13 21:56:13][INFO] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
[2023/07/13 21:56:13][INFO]  ---> System.MissingMethodException: Method not found: 'Void Microsoft.CodeAnalysis.CSharp.CSharpCompilationOptions..ctor(Microsoft.CodeAnalysis.OutputKind, Boolean, System.String, System.String, System.String, System.Collections.Generic.IEnumerable`1<System.String>, Microsoft.CodeAnalysis.OptimizationLevel, Boolean, Boolean, System.String, System.String, System.Collections.Immutable.ImmutableArray`1<Byte>, System.Nullable`1<Boolean>, Microsoft.CodeAnalysis.Platform, Microsoft.CodeAnalysis.ReportDiagnostic, Int32, System.Collections.Generic.IEnumerable`1<System.Collections.Generic.KeyValuePair`2<System.String,Microsoft.CodeAnalysis.ReportDiagnostic>>, Boolean, Boolean, Microsoft.CodeAnalysis.XmlReferenceResolver, Microsoft.CodeAnalysis.SourceReferenceResolver, Microsoft.CodeAnalysis.MetadataReferenceResolver, Microsoft.CodeAnalysis.AssemblyIdentityComparer, Microsoft.CodeAnalysis.StrongNameProvider, Boolean, Microsoft.CodeAnalysis.MetadataImportOptions, Microsoft.CodeAnalysis.CSharp.NullableContextOptions)'.
[2023/07/13 21:56:13][INFO]    at CscBench.DataflowBench()
[2023/07/13 21:56:13][INFO]    at CscBench.DatflowTest() in /home/helixbot/work/B60C0A13/w/AC4208EF/e/performance/src/benchmarks/micro/runtime/Roslyn/CscBench.cs:line 163
[2023/07/13 21:56:13][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_0.WorkloadActionNoUnroll(Int64 invokeCount) in /home/helixbot/work/B60C0A13/w/AC4208EF/e/performance/artifacts/bin/MicroBenchmarks/Release/net8.0/3a0b4299-0713-4c81-8f26-321d05a2c805/3a0b4299-0713-4c81-8f26-321d05a2c805.notcs:line 325
[2023/07/13 21:56:13][INFO]    at BenchmarkDotNet.Engines.Engine.RunIteration(IterationData data)
[2023/07/13 21:56:13][INFO]    at BenchmarkDotNet.Engines.EngineFactory.Jit(Engine engine, Int32 jitIndex, Int32 invokeCount, Int32 unrollFactor)
[2023/07/13 21:56:13][INFO]    at BenchmarkDotNet.Engines.EngineFactory.CreateReadyToRun(EngineParameters engineParameters)
[2023/07/13 21:56:13][INFO]    at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName) in /home/helixbot/work/B60C0A13/w/AC4208EF/e/performance/artifacts/bin/MicroBenchmarks/Release/net8.0/3a0b4299-0713-4c81-8f26-321d05a2c805/3a0b4299-0713-4c81-8f26-321d05a2c805.notcs:line 180
[2023/07/13 21:56:13][INFO]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
[2023/07/13 21:56:13][INFO]    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[2023/07/13 21:56:13][INFO]    --- End of inner exception stack trace ---
[2023/07/13 21:56:13][INFO]    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
[2023/07/13 21:56:13][INFO]    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2023/07/13 21:56:13][INFO]    at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args) in /home/helixbot/work/B60C0A13/w/AC4208EF/e/performance/artifacts/bin/MicroBenchmarks/Release/net8.0/3a0b4299-0713-4c81-8f26-321d05a2c805/3a0b4299-0713-4c81-8f26-321d05a2c805.notcs:line 57
```

**Comment by cincuranet** [comment]
Starting with build [20230717.6](https://dev.azure.com/dnceng/internal/_build/results?buildId=2223709&view=results) the benchmark is no longer failing.
