### ISSUE TITLE
[perf] iOS Maui blazor default startup didn't get the fully-drawn magic string event

### ISSUE THREAD

**Issue by kotlarmilos** [dotnet/performance#3148]
https://dev.azure.com/dnceng/internal/_build/results?buildId=2225910
```
[2023/07/20 01:42:04][INFO] {"count":16,"finished":1}
[2023/07/20 01:42:04][INFO] ==========
[2023/07/20 01:42:04][INFO] /private/tmp/helix/working/A9A00928/w/B1E70900/e/mauiblazorios/tmp/iteration0.logarchive
[2023/07/20 01:42:04][INFO] ==========
[2023/07/20 01:42:04][INFO] $ log show --predicate "(processIdentifier == 1511) && (composedMessage contains \"__MAUI_Blazor_WebView_OnAfterRender__\")" --info --style ndjson tmp/iteration0.logarchive
[2023/07/20 01:42:04][INFO] {"count":0,"finished":1}
[2023/07/20 01:42:04][INFO] ==========
[2023/07/20 01:42:04][INFO] /private/tmp/helix/working/A9A00928/w/B1E70900/e/mauiblazorios/tmp/iteration0.logarchive
[2023/07/20 01:42:04][INFO] ==========
Versions: {'mauiVersion': '8.0.0-nightly.8767+sha.15061214f-azdo.8112471.15061214f153f9ed81de921c34a9777d8c8a0230'}
Traceback (most recent call last):
  File "test.py", line 16, in <module>
    Runner(traits).run()
  File "/tmp/helix/working/A9A00928/p/shared/runner.py", line 763, in run
    raise Exception("Didn't get the fully-drawn magic string event.")
Exception: Didn't get the fully-drawn magic string event.
Removing app,tmp,traces,pub,bin,crossgen.out,__pycache__,emsdk if exist ...
Removing empty log files:
ls: /tmp/helix/working/A9A00928/w/B1E70900/uploads/xunit-*.xml: No such file or directory
+ exit_code=1
+ '[' -f /tmp/helix/working/A9A00928/w/B1E70900/e/.retry ']'
+ '[' -f /tmp/helix/working/A9A00928/w/B1E70900/e/.reboot ']'
+ exit 1
+ export _commandExitCode=1
+ _commandExitCode=1
+ export PYTHONPATH=:/etc/helix/scripts
+ PYTHONPATH=:/etc/helix/scripts
+ /usr/local/bin/python3 -u /tmp/helix/working/A9A00928/w/B1E70900/u/xharness-event-processor.py
Reporting 4 events from diagnostics file `/tmp/helix/working/A9A00928/w/B1E70900/e/diagnostics.json`
```

**Comment by kotlarmilos** [comment]
This is happening in the Blazor Maui scenario with the Native AOT. The app's end string is not being printed or detected. https://github.com/dotnet/performance/blob/d3e3154a893fae4e2093faa00f1505de8a051ba2/src/scenarios/mauiblazorios/pre.py#L26-L51

I will try to reproduce the failure locally.

/cc: @ivanpovazan

**Comment by kotlarmilos** [comment]
I tried the app locally and there is a fully-drawn magic string event. @LoopedBard3 Could the script for measuring startup terminate before the app logs the event?

**Comment by kotlarmilos** [comment]
I managed to reproduce the issue locally: https://github.com/xamarin/xamarin-macios/issues/19117.

**Comment by LoopedBard3** [comment]
It seems this is now happening with non-NativeAOT runs: https://dev.azure.com/dnceng/internal/_build/results?buildId=2355112&view=results (Net9.0 testing run hitting what appears to be the same issue).

**Comment by LoopedBard3** [comment]
Yes, this still seems to be the case for Mono runs. Here is a test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2379407&view=results that demonstrates this.
