### ISSUE TITLE
Pipelines are failing with "RuntimeError: Unable to determine the .NET SDK used for net8.0"

### ISSUE THREAD

**Issue by cincuranet** [dotnet/performance#3274]
```
Traceback (most recent call last):
  File "D:\a\1\s\scripts\ci_setup.py", line 487, in <module>
    __main(sys.argv[1:])
  File "D:\a\1\s\scripts\ci_setup.py", line 483, in __main
    main(CiSetupArgs(**vars(args)))
  File "D:\a\1\s\scripts\ci_setup.py", line 411, in main
    dotnet_version = dotnet.get_dotnet_version(target_framework_moniker, args.cli) if args.dotnet_versions == [] else args.dotnet_versions[0]
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\1\s\scripts\dotnet.py", line 581, in get_dotnet_version
    raise RuntimeError(
RuntimeError: Unable to determine the .NET SDK used for net8.0
```

**Comment by cincuranet** [comment]
The problem is `dotnet-install.ps1 -Architecture x64 -Channel 8.0 -Quality daily` installs `9.0.100-alpha.1.23416.26` at the moment and we're explicitly looking for `8.0` SDK.

**Comment by cincuranet** [comment]
It's fixed now. Artifacts are now properly published.
