### ISSUE TITLE
Daily Perf Index is not updating

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3278]
The daily perf index appears to not have updated since 08-14, around the time the indexgenerator automatic updating was added. I am taking a look into this.

This does not repro without publishing in VS.

**Comment by LoopedBard3** [comment]
This is the error I got when trying to run the generator locally. 
"Unhandled exception. System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.)
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at RazorLight.Compilation.RoslynCompilationService.CompileAndEmit(IGeneratedRazorTemplate razorTemplate)
   at RazorLight.Compilation.RazorTemplateCompiler.CompileAndEmitAsync(RazorLightProjectItem projectItem)
   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
   at RazorLight.Compilation.RazorTemplateCompiler.OnCacheMissAsync(String templateKey)
   at RazorLight.EngineHandler.CompileTemplateAsync(String key)
   at RazorLight.EngineHandler.CompileRenderAsync[T](String key, T model, ExpandoObject viewBag)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at IndexGenerator.Program.Main(String[] args)"
   
   The error from the logs is about not being able to get the blob storage so there may be multiple errors.

**Comment by LoopedBard3** [comment]
This is potentially related to the local error: https://github.com/toddams/RazorLight/issues/429

**Comment by LoopedBard3** [comment]
After more looking, the AggregateException may be local to just me. The current error is a 404 Resource does not exist.

**Comment by LoopedBard3** [comment]
Fix for the 404 error is out: https://dev.azure.com/dnceng/internal/_git/dotnet-performance-infra/pullrequest/33248. Will close this issue if runs work properly tomorrow.
