### ISSUE TITLE
Maui iOS setup is not propagating failure

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3380]
Maui scenario builds are failing during workload installs but the iOS Maui runs don't have this failure causing the job to fail.
```
[2023/10/04 17:54:01][INFO] ----------------------------------------------
  [2023/10/04 17:54:01][INFO] Initializing logger 2023-10-04 17:54:01.107681
  [2023/10/04 17:54:01][INFO] ----------------------------------------------
  
  Skipping NuGet package signature verification.
  Installing workload manifest microsoft.net.sdk.android version 34.0.0-rc.2.468...
  Installing workload manifest microsoft.net.sdk.ios version 16.4.8911-net8-rc2...
  Installing workload manifest microsoft.net.sdk.maccatalyst version 16.4.8911-net8-rc2...
  Installing workload manifest microsoft.net.sdk.macos version 13.3.8911-net8-rc2...
  Installing workload manifest microsoft.net.sdk.maui version 8.0.0-ci.net8.9366...
  Workload installation failed. Rolling back installed packs...
  Workload installation failed: Failed to install manifest microsoft.net.sdk.maui version 8.0.0-ci.net8.9366: microsoft.net.sdk.maui.manifest-8.0.100-rc.2::8.0.0-ci.net8.9366 is not found in NuGet feeds [https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/benchmark-dotnet-prerelease/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-95068821/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-26e0f822/nuget/v3/index.json"..](https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-eng/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet-public/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet6/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet7/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/dotnet8/nuget/v3/index.json;https://pkgs.dev.azure.com/xamarin/public/_packaging/SkiaSharp/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/benchmark-dotnet-prerelease/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-emsdk-95068821/nuget/v3/index.json;https://pkgs.dev.azure.com/dnceng/public/_packaging/darc-pub-dotnet-runtime-26e0f822/nuget/v3/index.json%22..)
  None
  Traceback (most recent call last):
    File "/Users/runner/work/1/s/src/scenarios/mauiios/pre.py", line 17, in <module>
      install_versioned_maui(precommands)
    File "/Users/runner/work/1/s/src/scenarios/shared/mauisharedpython.py", line 24, in install_versioned_maui
      precommands.install_workload('maui', workload_install_args) 
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    File "/Users/runner/work/1/s/src/scenarios/shared/precommands.py", line 284, in install_workload
      subprocess.run(["dotnet", "workload", "install", workloadid] + install_args, check=True)
    File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
      raise CalledProcessError(retcode, process.args,
  subprocess.CalledProcessError: Command '['dotnet', 'workload', 'install', 'maui', '--configfile', 'MauiNuGet.config', '--skip-sign-check', '--from-rollback-file', 'https://aka.ms/dotnet/maui/net8.0.json']' returned non-zero exit status 1.
    adding: mauiios/ (stored 0%)
    adding: mauiios/post.py (deflated 26%)
    adding: mauiios/MauiNuGet.config (deflated 76%)
    adding: mauiios/__pycache__/ (stored 0%)
    adding: mauiios/__pycache__/test.cpython-311.pyc (deflated 29%)
    adding: mauiios/test.py (deflated 45%)
    adding: mauiios/pre.py (deflated 56%)
  Removing app,tmp,traces,pub,bin,crossgen.out,__pycache__,emsdk if exist ...
```

**Comment by LoopedBard3** [comment]
This appears to no longer be an issue, closing.
