### ISSUE TITLE
Mono AOT runs failing due to precompiling failure

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#3394]
Both Mono AOT x64 and Arm64 runs are failing with precompiling failed errors. Such as this one below taken from a x64 run. Likely related to the same cause as: https://github.com/dotnet/runtime/issues/93188. This issue is to track the fixing of these runs.
```
[2023/10/09 11:20:12][INFO]   Mono Ahead of Time compiler - compiling assembly /home/helixbot/work/A53D09AC/w/AE4D09E4/e/performance/artifacts/bin/MicroBenchmarks/Release/net8.0/Job-VRQHGH/bin/net8.0/linux-x64/publish/System.Private.CoreLib.dll
[2023/10/09 11:20:12][INFO]   AOTID 82036FB0-6B1F-7255-7968-04C71C6F118A
[2023/10/09 11:20:12][INFO]   * Assertion at /__w/1/s/src/mono/mono/mini/mini-llvm.c:10032, condition `LLVMTypeOf (lhs) == LLVMTypeOf (rhs)' not met
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   	Native Crash Reporting
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   Got a SIGABRT while executing native code. This usually indicates
[2023/10/09 11:20:12][INFO]   a fatal error in the mono runtime or one of the native libraries
[2023/10/09 11:20:12][INFO]   used by your application.
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   	Native stacktrace:
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   	0x56354d625ef1 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d5c91ee - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d625791 - Unknown
[2023/10/09 11:20:12][INFO]   	0x7f84bac42520 - Unknown
[2023/10/09 11:20:12][INFO]   	0x7f84bac969fc - Unknown
[2023/10/09 11:20:12][INFO]   	0x7f84bac42476 - Unknown
[2023/10/09 11:20:12][INFO]   	0x7f84bac287f3 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d3ece05 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d4002a6 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d3ed26f - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d3ed3d5 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d3ed417 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d67f336 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d668003 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d666159 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d532892 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d5a82e3 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d598964 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d59429e - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d520c5b - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d51cc20 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d3dd2ba - Unknown
[2023/10/09 11:20:12][INFO]   	0x7f84bac29d90 - Unknown
[2023/10/09 11:20:12][INFO]   	0x7f84bac29e40 - Unknown
[2023/10/09 11:20:12][INFO]   	0x56354d3dd189 - Unknown
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   	External Debugger Dump:
[2023/10/09 11:20:12][INFO]   =================================================================
[2023/10/09 11:20:12][INFO]   [New LWP 73872]
[2023/10/09 11:20:12][INFO]   [Thread debugging using libthread_db enabled]
[2023/10/09 11:20:12][INFO]   Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[2023/10/09 11:20:12][INFO]   0x00007f84bacea42f in __GI___wait4 (pid=73950, stat_loc=0x7fffb9034600, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
[2023/10/09 11:20:12][INFO]   30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[2023/10/09 11:20:12][INFO]     Id   Target Id                                          Frame
[2023/10/09 11:20:12][INFO]   * 1    Thread 0x7f84baed0480 (LWP 73871) "mono-aot-cross" 0x00007f84bacea42f in __GI___wait4 (pid=73950, stat_loc=0x7fffb9034600, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
[2023/10/09 11:20:12][INFO]     2    Thread 0x7f84b9fff640 (LWP 73872) "SGen worker"    __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x56354de924d8) at ./nptl/futex-internal.c:57
[2023/10/09 11:20:12][INFO]   Thread 2 (Thread 0x7f84b9fff640 (LWP 73872) "SGen worker"):
[2023/10/09 11:20:12][INFO]   #0  __futex_abstimed_wait_common64 (private=0, cancel=true, abstime=0x0, op=393, expected=0, futex_word=0x56354de924d8) at ./nptl/futex-internal.c:57
[2023/10/09 11:20:12][INFO]   #1  __futex_abstimed_wait_common (cancel=true, private=0, abstime=0x0, clockid=0, expected=0, futex_word=0x56354de924d8) at ./nptl/futex-internal.c:87
[2023/10/09 11:20:12][INFO]   #2  __GI___futex_abstimed_wait_cancelable64 (futex_word=futex_word@entry=0x56354de924d8, expected=expected@entry=0, clockid=clockid@entry=0, abstime=abstime@entry=0x0, private=private@entry=0) at ./nptl/futex-internal.c:139
[2023/10/09 11:20:12][INFO]   #3  0x00007f84bac93a41 in __pthread_cond_wait_common (abstime=0x0, clockid=0, mutex=0x56354de92488, cond=0x56354de924b0) at ./nptl/pthread_cond_wait.c:503
[2023/10/09 11:20:12][INFO]   #4  ___pthread_cond_wait (cond=0x56354de924b0, mutex=0x56354de92488) at ./nptl/pthread_cond_wait.c:627
[2023/10/09 11:20:12][INFO]   #5  0x000056354d4157d3 in ?? ()
[2023/10/09 11:20:12][INFO]   #6  0x00007f84bac94ac3 in start_thread (arg=<optimized out>) at ./nptl/pthread_create.c:442
[2023/10/09 11:20:12][INFO]   #7  0x00007f84bad26a40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
[2023/10/09 11:20:12][INFO]   Thread 1 (Thread 0x7f84baed0480 (LWP 73871) "mono-aot-cross"):
[2023/10/09 11:20:12][INFO]   #0  0x00007f84bacea42f in __GI___wait4 (pid=73950, stat_loc=0x7fffb9034600, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
[2023/10/09 11:20:12][INFO]   #1  0x000056354d626022 in ?? ()
[2023/10/09 11:20:12][INFO]   #2  0x000056354d5c91ee in ?? ()
[2023/10/09 11:20:12][INFO]   #3  0x000056354d625791 in ?? ()
[2023/10/09 11:20:12][INFO]   #4  <signal handler called>
[2023/10/09 11:20:12][INFO]   #5  __pthread_kill_implementation (no_tid=0, signo=6, threadid=140208048505984) at ./nptl/pthread_kill.c:44
[2023/10/09 11:20:12][INFO]   #6  __pthread_kill_internal (signo=6, threadid=140208048505984) at ./nptl/pthread_kill.c:78
[2023/10/09 11:20:12][INFO]   #7  __GI___pthread_kill (threadid=140208048505984, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
[2023/10/09 11:20:12][INFO]   #8  0x00007f84bac42476 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
[2023/10/09 11:20:12][INFO]   #9  0x00007f84bac287f3 in __GI_abort () at ./stdlib/abort.c:79
[2023/10/09 11:20:12][INFO]   #10 0x000056354d3ece05 in ?? ()
[2023/10/09 11:20:12][INFO]   #11 0x000056354d4002a6 in ?? ()
[2023/10/09 11:20:12][INFO]   #12 0x000056354d3ed26f in ?? ()
[2023/10/09 11:20:12][INFO]   #13 0x000056354d3ed3d5 in ?? ()
[2023/10/09 11:20:12][INFO]   #14 0x000056354d3ed417 in ?? ()
[2023/10/09 11:20:12][INFO]   #15 0x000056354d67f336 in ?? ()
[2023/10/09 11:20:12][INFO]   #16 0x000056354d668003 in ?? ()
[2023/10/09 11:20:12][INFO]   #17 0x000056354d666159 in ?? ()
[2023/10/09 11:20:12][INFO]   #18 0x000056354d532892 in ?? ()
[2023/10/09 11:20:12][INFO]   #19 0x000056354d5a82e3 in ?? ()
[2023/10/09 11:20:12][INFO]   #20 0x000056354d598964 in ?? ()
[2023/10/09 11:20:12][INFO]   #21 0x000056354d59429e in ?? ()
[2023/10/09 11:20:12][INFO]   #22 0x000056354d520c5b in ?? ()
[2023/10/09 11:20:12][INFO]   #23 0x000056354d51cc20 in ?? ()
[2023/10/09 11:20:12][INFO]   #24 0x000056354d3dd2ba in ?? ()
[2023/10/09 11:20:12][INFO]   #25 0x00007f84bac29d90 in __libc_start_call_main (main=main@entry=0x56354d3dd290, argc=argc@entry=2, argv=argv@entry=0x7fffb9037878) at ../sysdeps/nptl/libc_start_call_main.h:58
[2023/10/09 11:20:12][INFO]   #26 0x00007f84bac29e40 in __libc_start_main_impl (main=0x56354d3dd290, argc=2, argv=0x7fffb9037878, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffb9037868) at ../csu/libc-start.c:392
[2023/10/09 11:20:12][INFO]   #27 0x000056354d3dd189 in ?? ()
[2023/10/09 11:20:12][INFO]   [Inferior 1 (process 73871) detached]
```

**Comment by LoopedBard3** [comment]
Mono AOT x64 and arm64 runs are green again.
