### ISSUE TITLE
PerfTiger119 hitting errors when importing azure.storage.blob

### ISSUE THREAD

**Issue by LoopedBard3** [dotnet/performance#4242]
PerfTiger119 appears to be hitting errors importing azure.storage.blob:
```
Traceback (most recent call last):
  File "C:\h\w\AD00097E\w\A8140924\e\performance\scripts\benchmarks_ci.py", line 361, in <module>
    main(sys.argv[1:])
  File "C:\h\w\AD00097E\w\A8140924\e\performance\scripts\benchmarks_ci.py", line 349, in main
    import upload
  File "C:\h\w\AD00097E\w\A8140924\e\performance\scripts\upload.py", line 3, in <module>
    from azure.storage.blob import BlobClient, ContentSettings
  File "D:\python3\lib\site-packages\azure\storage\blob\__init__.py", line 11, in <module>
    from ._blob_client import BlobClient
  File "D:\python3\lib\site-packages\azure\storage\blob\_blob_client.py", line 24, in <module>
    from ._shared.encryption import generate_blob_encryption_data
  File "D:\python3\lib\site-packages\azure\storage\blob\_shared\encryption.py", line 15, in <module>
    from cryptography.hazmat.backends import default_backend
ValueError: source code string cannot contain null bytes
```
This is being seen only on this machine so far and can be found in the failing micro runs in these two pipeline runs:
https://dev.azure.com/dnceng/internal/_build/results?buildId=2463158&view=results https://dev.azure.com/dnceng/internal/_build/results?buildId=2463346&view=results

Taking it out of rotation so we can more fully investigate and to get the few runs green again. (https://github.com/dotnet/dnceng/issues/2977)

FYI: @DrewScoggins @caaavik-msft

**Comment by caaavik-msft** [comment]
This is now fixed. Somehow the python install on PERFTIGER119 is corrupted with whole packages inside site-packages missing important metadata files and source files being replaced with null bytes. All pip commands that attempted to reinstall these packages were failing because of the missing metadata. With #4339 merged we are now correctly using the python venv so the runs won't break if the machine has any issues with the global site packages.
