### ISSUE TITLE
Real-world JitBench Run Failed due to 404 (Not Found)

### ISSUE THREAD

**Issue by t-takhan** [dotnet/performance#497]
I was trying to run real-word JitBench benchmark following [this guide](https://github.com/dotnet/performance/blob/master/src/benchmarks/real-world/JitBench/README.md) on ubuntu 18.04.2. However, running the command `dotnet run -c Release -- --netcoreapp-version 2.0` gives me following error:

```
  === CONFIGURATION ===

DotnetFrameworkVersion: 2.0
DotnetSdkVersion:       2.0.0
PrivateCoreCLRBinDir:
Architecture:           X64
OutputDir:              /tmp/Scenarios_2019_05_23_10_36_24_5066
Iterations:             11
UseExistingSetup:       False
Configurations:         Default


Benchmark run in progress...
Verbose log: /tmp/Scenarios_2019_05_23_10_36_24_5066/RealWorld_log.txt


Unhandled Exception: System.AggregateException: One or more errors occurred. (One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).)) ---> System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 404 (Not Found).) ---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 404 (Not Found).
   at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()
   at System.Net.Http.HttpClient.FinishGetStreamAsync(Task`1 getTask)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at RealWorld.FileTasks.Download(String remotePath, String localPath, ITestOutputHelper output) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Utilities/FileTasks.cs:line 36
   at RealWorld.FileTasks.DownloadAndUnzip(String remotePath, String localExpandedDirPath, ITestOutputHelper output, Boolean deleteTempFiles) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Utilities/FileTasks.cs:line 24
   at RealWorld.DotNetSetup.Run(ITestOutputHelper output) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Utilities/DotNetSetup.cs:line 94
   at RealWorld.TestRun.PrepareDotNet(ITestOutputHelper output) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Runner/TestRun.cs:line 160
   at RealWorld.TestRun.SetupBenchmarks(ITestOutputHelper output) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Runner/TestRun.cs:line 133
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at RealWorld.TestRun.Run(ITestOutputHelper output) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Runner/TestRun.cs:line 45
   at RealWorld.Program.Main(String[] args) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Program.cs:line 36
```

It seems that dotnet sdk for [2.0](https://dotnetcli.azureedge.net/dotnet/Sdk/2.0.0/dotnet-sdk-2.0.0-linux-x64.zip) does not exist anymore.

Next, when I try running 2.2 with this command, `dotnet run -c Release -- --netcoreapp-version 2.2`, I get following error message:
```
Unhandled Exception: System.NotSupportedException: Version 2.2 doesn't have a known TFM
   at RealWorld.DotNetSetup.GetTargetFrameworkMonikerForFrameworkVersion(String runtimeVersion) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Utilities/DotNetSetup.cs:line 252
   at RealWorld.Program.ConfigureTestRun(CommandLineOptions options) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Program.cs:line 78
   at RealWorld.Program.Main(String[] args) in /home/takhandipu/performance/src/benchmarks/real-world/JitBench/Program.cs:line 20
```
Even though my dotnet version is 2.2.300 and `dotnet build -c Release` succeeded without any error or warning.

**Comment by alpencolt** [comment]
I've faced with the same error:
```
dotnet run --framework netcoreapp3.0 -c Release --netcoreapp-version 2.1
```
Content of `/tmp/Scenarios_2019_10_04_01_59_38_3795/RealWorld_log.txt`:
```
  === CONFIGURATION ===

DotnetFrameworkVersion: 2.1
DotnetSdkVersion:       2.2.0-preview1-007558
PrivateCoreCLRBinDir:   
Architecture:           X64
OutputDir:              /tmp/Scenarios_2019_10_04_01_59_38_3795
Iterations:             11
UseExistingSetup:       False
Configurations:         Default

  === SETUP ===

Acquiring DotNet
{
    Downloading: https://dotnetcli.azureedge.net/dotnet/Sdk/2.2.0-preview1-007558/dotnet-sdk-2.2.0-preview1-007558-linux-x64.zip -> /tmp/069a9e21-30a2-4e6a-96cf-41968e588760.zip
}
```

Is the description in README correct?

**Comment by adamsitnik** [comment]
We have not updated these benchmarks in a while and I am afraid that we are not going to fix them anytime soon.

The good news is that @billwert is working on a new and better way of running real world benchmarks, and we are most probably soon going to have a new portfolio of real world benchmarks.

**Comment by adamsitnik** [comment]
The benchmark is not used anymore and has been removed in #1566
