### ISSUE TITLE
System.DllNotFoundException: Unable to load DLL 'libgdiplus': The specified module could not be found.

### ISSUE THREAD

**Issue by naricc** [dotnet/performance#621]
Platform: MacOS Mojave

I checked out the latest performance (as of today), and I built the microbenchmakrs like so (in the /src/benchmarks/micro diretory):

dotnet build -c Release

Trying to use dotnet run, most commands will produce an error about missing libgdiplus (full stack trace below). But libgdiplus is installed as part of mono at: /Library/Frameworks/Mono.framework/Versions/Current/lib/libgdiplus.dylib, which I think it should be able to find? Do I need to set some additional environment variable?

Command and full stack trace:

> dotnet run -c release -f netcoreapp3.0 --list flat
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeInitializationException: The type initializer for 'Gdip' threw an exception.
 ---> System.DllNotFoundException: Unable to load DLL 'libgdiplus': The specified module could not be found.
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipCreateBitmapFromScan0(Int32 width, Int32 height, Int32 stride, Int32 format, HandleRef scan0, IntPtr& bitmap)
   at System.Drawing.Bitmap..ctor(Int32 width, Int32 height, PixelFormat format)
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData.CreateTestImage(ImageFormat format) in /Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/corefx/System.Drawing/Perf_Image_Load.cs:line 94
   at System.Drawing.Tests.Perf_Image_Load.ImageTestData..ctor(ImageFormat format) in /Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/corefx/System.Drawing/Perf_Image_Load.cs:line 78
   at System.Drawing.Tests.Perf_Image_Load.CreateTestCases() in /Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/corefx/System.Drawing/Perf_Image_Load.cs:line 53
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()
   at System.Drawing.Tests.Perf_Image_Load.ImageFormats() in /Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/corefx/System.Drawing/Perf_Image_Load.cs:line 20
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetValidValuesForParamsSource(Type parentType, String sourceName)
   at BenchmarkDotNet.Running.BenchmarkConverter.GetArgumentsDefinitions(MethodInfo benchmark, Type target)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.BenchmarkConverter.MethodsToBenchmarksWithFullConfig(Type containingType, MethodInfo[] benchmarkMethods, ImmutableConfig immutableConfig)
   at BenchmarkDotNet.Running.BenchmarkConverter.TypeToBenchmarks(Type type, IConfig config)
   at BenchmarkDotNet.Running.TypeFilter.<>c__DisplayClass1_0.<Filter>b__0(Type type)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at BenchmarkDotNet.Running.TypeFilter.Filter(IConfig effectiveConfig, IEnumerable`1 types)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.PrintList(ILogger nonNullLogger, IConfig effectiveConfig, IReadOnlyList`1 allAvailableTypesWithRunnableBenchmarks, CommandLineOptions options)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.RunWithDirtyAssemblyResolveHelper(String[] args, IConfig config)
   at BenchmarkDotNet.Running.BenchmarkSwitcher.Run(String[] args, IConfig config)
   at MicroBenchmarks.Program.Main(String[] args) in /Users/naricc/workspace/perf-mono/performance/src/benchmarks/micro/Program.cs:line 35

**Comment by billwert** [comment]
Because CoreCLR and mono are distinct, mono specific installation paths aren't considered.

I just fix this normally by installing libgdiplus itself.

**Comment by billwert** [comment]
@adamsitnik has a PR which will print a better error, also.
