### ISSUE TITLE
dotnet.py fails with an AttributeError

### ISSUE THREAD

**Issue by noahfalk** [dotnet/performance#725]
I just cloned the repo and tried to run dotnet.py. I'm not sure I am doing it correctly, but the [Prerequisites page](https://github.com/dotnet/performance/blob/master/docs/prerequisites.md) doesn't offer specific guidance:

     Optionally, you could use dotnet.py to to download the DotNet Cli locally.

Repro:
1) Create new Ubuntu VM 18.04.2 LTS, start terminal
2) git clone https://github.com/dotnet/performance
3) cd performance
4) sudo apt install python3
5) scripts/dotnet.py
Expected behavior: It downloads a recent version of .NET
Actual behavior: Command outputs this text and exits:
```
Traceback (most recent call last):
  File "scripts/dotnet.py", line 692, in <module>
    __main(argv[1:])
  File "scripts/dotnet.py", line 681, in __main
    setup_loggers(verbose=args.verbose)
AttributeError: 'Namespace' object has no attribute 'verbose'
```

**Comment by noahfalk** [comment]
Poking at it more it appears including the argument "install" is intended. That also didn't work with a different error, but I'll leave this issue as-is to represent what happens when users guess and don't attempt to be resourceful when things aren't working : )
