### ISSUE TITLE
CI broken

### ISSUE THREAD

**Issue by billwert** [dotnet/performance#878]
Not sure what the root cause is yet, but wanted to get an issue logged so folks know I'm working on it.

Superficial cause is that the SDK is including a commit hash in the .version file contained within that is not actually in core-sdk, so our call into github fails:
```
Getting commit info for framework netcoreapp3.0 commit_sha 4f9b335ba53454450746dbdb7a01303845172126 repository None
Traceback (most recent call last):
  File "E:\source\performance\scripts\ci_setup.py", line 254, in <module>
    __main(sys.argv[1:])
  File "E:\source\performance\scripts\ci_setup.py", line 221, in __main
    source_timestamp = dotnet.get_commit_date(target_framework_moniker, commit_sha, repo_url)
  File "E:\source\performance\scripts\dotnet.py", line 449, in get_commit_date
    with urlopen(url) as response:
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 531, in open
    response = meth(req, response)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 641, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 569, in error
    return self._call_chain(*args)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Program Files (x86)\Python37-32\lib\urllib\request.py", line 649, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 422: Unprocessable Entity
```

Other weirdness is the currently served SDK comes down from here:
```
[2019/09/13 16:34:17][INFO] dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-cesar1-014246/dotnet-sdk-3.0.100-cesar1-014246-win-x64.zip
[2019/09/13 16:34:18][INFO] dotnet-install: Extracting zip from https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-cesar1-014246/dotnet-sdk-3.0.100-cesar1-014246-win-x64.zip
```

Note `cesar1` - not sure what's up with that.

cc: @leecow @mmitche

**Comment by billwert** [comment]
This particular issue got fixed, but another issue is hitting now: 
```
PS C:\Users\billwert > powershell e:\work\scratch\dotnet-install.ps1 -InstallDir E:\source\performance\tools\dotnet\x64 -Architecture x64 -Channel release/3.0.1xx
dotnet-install: Downloading link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-rc2-014263/dotnet-sdk-3.0.100-rc2-014263-win-x64.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-rc2-014263/dotnet-sdk-3.0.100-rc2-014263-win-x64.zip
dotnet-install: Downloading legacy link: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-rc2-014263/dotnet-dev-win-x64.3.0.100-rc2-014263.zip
dotnet-install: Cannot download: https://dotnetcli.azureedge.net/dotnet/Sdk/3.0.100-rc2-014263/dotnet-dev-win-x64.3.0.100-rc2-014263.zip
Could not find/download: ".NET Core SDK" with version = 3.0.100-rc2-014263
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support
At E:\work\scratch\dotnet-install.ps1:622 char:5
+     throw "Could not find/download: `"$assetName`" with version = $Sp ...
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Could not find/...ET Core support:String) [], RuntimeException
    + FullyQualifiedErrorId : Could not find/download: ".NET Core SDK" with version = 3.0.100-rc2-014263
Refer to: https://aka.ms/dotnet-os-lifecycle for information on .NET Core support

```

Working on this one.
